import { PlatformCommandButton } from "@/components/platform/platform-command";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { PageHeader } from "@/components/ui/page-header";
import { requirePlatformContext } from "@/lib/context/platform-context";
import { maintenanceState } from "@/lib/modules/platform/platform-control.query";

export const metadata = { title: "Maintenance" };
const controls = [{ key: "maintenance.enabled", prop: "enabled", label: "Maintenance mode", description: "Route tenant UI to the maintenance state and refuse tenant APIs." }, { key: "maintenance.readOnly", prop: "readOnly", label: "Read-only mode", description: "Allow tenant reads while refusing mutations." }, { key: "maintenance.disableUploads", prop: "disableUploads", label: "Disable uploads", description: "Refuse upload and document-version mutations." }, { key: "maintenance.disableNewLogins", prop: "disableNewLogins", label: "Disable new tenant logins", description: "Keep Platform Admin access available while refusing new tenant sessions." }, { key: "maintenance.disable3DProcessing", prop: "disable3DProcessing", label: "Disable 3D processing", description: "Pause new 3D processing and publishing operations." }] as const;
export default async function MaintenancePage() { await requirePlatformContext(); const state = await maintenanceState(); return <div className="space-y-5"><PageHeader title="Maintenance controls" description="Every safety state requires a reason, confirmation through the dialog and a critical audit event." /><div className="space-y-3">{controls.map((control) => { const active = state[control.prop]; return <Card key={control.key} className="flex flex-wrap items-center justify-between gap-5 p-5"><div className="max-w-3xl"><div className="flex items-center gap-2"><h2 className="text-body font-semibold text-fg">{control.label}</h2><Badge tone={active ? "warning" : "success"}>{active ? "ENABLED" : "OFF"}</Badge></div><p className="mt-1 text-table text-fg-muted">{control.description}</p></div><PlatformCommandButton label={active ? "Turn off" : "Enable"} title={`${active ? "Turn off" : "Enable"} ${control.label.toLowerCase()}?`} description="This changes live platform behavior immediately and is recorded in the audit trail." action="maintenance.save" fixed={{ key: control.key, enabled: !active }} reasonOnly destructive={!active} variant={active ? "secondary" : "danger"} success={`${control.label} ${active ? "disabled" : "enabled"}.`} /></Card>; })}</div></div>; }
