import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { PageHeader } from "@/components/ui/page-header";
import { Table, TableBody, TableCell, TableHead, TableHeaderCell, TableRow } from "@/components/ui/table";
import { requirePlatformContext } from "@/lib/context/platform-context";
import { platformOperations } from "@/lib/modules/platform/platform-control.query";

export const metadata = { title: "Storage" };
const bytes = (value: string) => { const n = Number(value); return n < 1024 ? `${n} B` : n < 1024 ** 2 ? `${(n / 1024).toFixed(1)} KB` : n < 1024 ** 3 ? `${(n / 1024 ** 2).toFixed(1)} MB` : `${(n / 1024 ** 3).toFixed(2)} GB`; };
export default async function StoragePage() { const context = await requirePlatformContext(); const data = await platformOperations(context); const total = data.storage.reduce((sum, row) => sum + BigInt(row.usedBytes), BigInt(0)); return <div className="space-y-5"><PageHeader title="Storage" description="Metadata and usage only. Opening sensitive tenant files requires explicit support access." /><div className="grid gap-4 sm:grid-cols-3"><Card className="p-5"><p className="text-table text-fg-muted">Total storage</p><p className="mt-2 text-3xl font-semibold">{bytes(total.toString())}</p></Card><Card className="p-5"><p className="text-table text-fg-muted">Files</p><p className="mt-2 text-3xl font-semibold">{data.storage.reduce((sum, row) => sum + row.fileCount, 0)}</p></Card><Card className="p-5"><p className="text-table text-fg-muted">Failed / expired uploads</p><p className="mt-2 text-3xl font-semibold">{data.failedUploads}</p></Card></div><section className="nesto-card p-5"><Table flush aria-label="Storage by company"><TableHead><TableRow><TableHeaderCell>Company</TableHeaderCell><TableHeaderCell>Parent Group</TableHeaderCell><TableHeaderCell>Files</TableHeaderCell><TableHeaderCell>Storage</TableHeaderCell><TableHeaderCell>Status</TableHeaderCell></TableRow></TableHead><TableBody>{data.storage.map((row) => <TableRow key={row.companyId}><TableCell>{row.company.name}</TableCell><TableCell>{row.company.parentGroup.name}</TableCell><TableCell>{row.fileCount}</TableCell><TableCell>{bytes(row.usedBytes)}</TableCell><TableCell><Badge tone="success">TRACKED</Badge></TableCell></TableRow>)}</TableBody></Table></section></div>; }
