import { Badge } from "@/components/ui/badge";
import { PageHeader } from "@/components/ui/page-header";
import { adminRoleName } from "@/components/platform/admin-roles";
import { Table, TableBody, TableCell, TableHead, TableHeaderCell, TableRow } from "@/components/ui/table";
import { requirePlatformContext } from "@/lib/context/platform-context";
import { getTranslations } from "@/lib/i18n/server";
import { listRolePermissionRegistry } from "@/lib/modules/platform/platform-control.query";

export async function generateMetadata() { const t = await getTranslations("adminAccess"); return { title: t("users.roles.metaTitle") }; }
export default async function RolesPage() { const t = await getTranslations("adminAccess"); const tr = await getTranslations("roles"); const context = await requirePlatformContext(); const data = await listRolePermissionRegistry(context); return <div className="space-y-6"><PageHeader title={t("users.roles.title")} description={t("users.roles.description")} /><div className="grid gap-5 xl:grid-cols-2"><section className="nesto-card p-5"><h2 className="mb-4 text-card font-semibold text-fg">{t("users.roles.rolesHeading")}</h2><Table stack flush aria-label={t("users.roles.rolesLabel")}><TableHead><TableRow><TableHeaderCell>{t("users.roles.cols.role")}</TableHeaderCell><TableHeaderCell>{t("users.roles.cols.permissions")}</TableHeaderCell><TableHeaderCell>{t("users.roles.cols.members")}</TableHeaderCell></TableRow></TableHead><TableBody>{data.roles.map((role) => <TableRow key={role.id}><TableCell><span className="font-medium text-fg">{adminRoleName(tr, role.name)}</span><p className="font-mono text-micro text-fg-subtle">{role.key}</p></TableCell><TableCell>{role._count.permissions}</TableCell><TableCell>{role._count.members}</TableCell></TableRow>)}</TableBody></Table></section><section className="nesto-card p-5"><h2 className="mb-4 text-card font-semibold text-fg">{t("users.roles.registryHeading")}</h2><div className="max-h-[720px] overflow-auto"><Table stack flush aria-label={t("users.roles.permissionsLabel")}><TableHead><TableRow><TableHeaderCell>{t("users.roles.cols.permission")}</TableHeaderCell><TableHeaderCell>{t("users.roles.cols.module")}</TableHeaderCell><TableHeaderCell>{t("users.roles.cols.roles")}</TableHeaderCell></TableRow></TableHead><TableBody>{data.permissions.map((permission) => <TableRow key={permission.id}><TableCell><span className="font-mono text-meta text-fg">{permission.key}</span><p className="text-micro text-fg-subtle">{permission.description ?? permission.action}</p></TableCell><TableCell><Badge>{permission.module}</Badge></TableCell><TableCell>{permission._count.roles}</TableCell></TableRow>)}</TableBody></Table></div></section></div></div>; }
