import { PlatformCommandButton } from "@/components/platform/platform-command";
import { Badge } from "@/components/ui/badge";
import { PageHeader } from "@/components/ui/page-header";
import { Table, TableBody, TableCell, TableHead, TableHeaderCell, TableRow } from "@/components/ui/table";
import { getTranslations } from "@/lib/i18n/server";
import { enumLabel } from "@/lib/i18n/modules/adminAccess/enum-label";
import { adminRoleName } from "@/components/platform/admin-roles";
import { MEMBERSHIP_ROLE_KEYS } from "@/config/roles";
import { requirePlatformContext } from "@/lib/context/platform-context";
import { listPlatformCompanies, listPlatformMemberships, listPlatformUsers } from "@/lib/modules/platform/platform-control.query";

export async function generateMetadata() { const t = await getTranslations("adminAccess"); return { title: t("users.memberships.metaTitle") }; }
export default async function MembershipsPage() {
  const t = await getTranslations("adminAccess");
  const tr = await getTranslations("roles");
  const roleOptions = MEMBERSHIP_ROLE_KEYS.map((value) => ({ value, label: tr(`${value}.label`) }));
  const statusOptions = ["ACTIVE", "INVITED", "INACTIVE", "SUSPENDED"].map((value) => ({ value, label: enumLabel(t, "enums.accountStatus", value) }));
  const context = await requirePlatformContext(); const [memberships, companies, users] = await Promise.all([listPlatformMemberships(context), listPlatformCompanies(context), listPlatformUsers(context)]);
  return <div className="space-y-5"><PageHeader title={t("users.memberships.title")} description={t("users.memberships.description")} actions={<PlatformCommandButton label={t("users.memberships.create")} title={t("users.memberships.createTitle")} action="membership.create" variant="primary" success={t("users.memberships.created")} fields={[{ name: "userId", label: t("users.memberships.fields.user"), type: "select", required: true, options: users.filter((row) => !row.platformAccess).map((row) => ({ value: row.id, label: `${row.firstName} ${row.lastName} (${row.username})` })) }, { name: "companyId", label: t("users.memberships.fields.company"), type: "select", required: true, options: companies.map((row) => ({ value: row.id, label: `${row.parentGroup.name} · ${row.name}` })) }, { name: "roleKey", label: t("users.memberships.fields.role"), type: "select", required: true, options: roleOptions }, { name: "status", label: t("users.memberships.fields.status"), type: "select", required: true, options: statusOptions }, { name: "jobTitle", label: t("users.memberships.fields.jobTitle"), type: "text" }, { name: "reason", label: t("users.memberships.fields.reason"), type: "textarea", required: true }]} initial={{ status: "ACTIVE" }} />} />
  <section className="nesto-card p-5"><Table stack aria-label={t("users.memberships.tableLabel")}><TableHead><TableRow><TableHeaderCell>{t("users.memberships.cols.person")}</TableHeaderCell><TableHeaderCell>{t("users.memberships.cols.parentGroup")}</TableHeaderCell><TableHeaderCell>{t("users.memberships.cols.company")}</TableHeaderCell><TableHeaderCell>{t("users.memberships.cols.role")}</TableHeaderCell><TableHeaderCell>{t("users.memberships.cols.department")}</TableHeaderCell><TableHeaderCell>{t("users.memberships.cols.status")}</TableHeaderCell><TableHeaderCell /></TableRow></TableHead><TableBody>{memberships.map((row) => <TableRow key={row.id}><TableCell><span className="font-medium text-fg">{row.user.firstName} {row.user.lastName}</span><p className="font-mono text-micro text-fg-subtle">{row.user.username}</p></TableCell><TableCell>{row.company.parentGroup.name}</TableCell><TableCell>{row.company.name}</TableCell><TableCell>{adminRoleName(tr, row.role.name)}</TableCell><TableCell>{row.department?.name ?? "—"}</TableCell><TableCell><Badge tone={row.status === "ACTIVE" ? "success" : "danger"}>{enumLabel(t, "enums.accountStatus", row.status)}</Badge></TableCell><TableCell><PlatformCommandButton label={t("common.edit")} title={t("users.memberships.editTitle")} action="membership.update" fixed={{ membershipId: row.id }} fields={[{ name: "roleKey", label: t("users.memberships.fields.role"), type: "select", required: true, options: roleOptions }, { name: "status", label: t("users.memberships.fields.status"), type: "select", required: true, options: statusOptions }, { name: "reason", label: t("users.memberships.fields.reason"), type: "textarea", required: true }]} initial={{ roleKey: row.role.key, status: row.status }} success={t("users.memberships.updated")} /></TableCell></TableRow>)}</TableBody></Table></section></div>;
}
