import { PlatformCommandButton } from "@/components/platform/platform-command";
import { Badge } from "@/components/ui/badge";
import { PageHeader } from "@/components/ui/page-header";
import { Table, TableBody, TableCell, TableHead, TableHeaderCell, TableRow } from "@/components/ui/table";
import { MEMBERSHIP_ROLE_KEYS, roleLabel } from "@/config/roles";
import { requirePlatformContext } from "@/lib/context/platform-context";
import { listPlatformCompanies, listPlatformMemberships, listPlatformUsers } from "@/lib/modules/platform/platform-control.query";

export const metadata = { title: "Memberships" };
const roleOptions = MEMBERSHIP_ROLE_KEYS.map((value) => ({ value, label: roleLabel(value) }));
const statusOptions = ["ACTIVE", "INVITED", "INACTIVE", "SUSPENDED"].map((value) => ({ value, label: value }));

export default async function MembershipsPage() {
  const context = await requirePlatformContext(); const [memberships, companies, users] = await Promise.all([listPlatformMemberships(context), listPlatformCompanies(context), listPlatformUsers(context)]);
  return <div className="space-y-5"><PageHeader title="Memberships" description="The user-to-company role binding that drives tenant access." actions={<PlatformCommandButton label="Create membership" title="Create membership" action="membership.create" variant="primary" success="Membership created." fields={[{ name: "userId", label: "User", type: "select", required: true, options: users.filter((row) => !row.platformAccess).map((row) => ({ value: row.id, label: `${row.firstName} ${row.lastName} (${row.username})` })) }, { name: "companyId", label: "Company", type: "select", required: true, options: companies.map((row) => ({ value: row.id, label: `${row.parentGroup.name} · ${row.name}` })) }, { name: "roleKey", label: "Role", type: "select", required: true, options: roleOptions }, { name: "status", label: "Status", type: "select", required: true, options: statusOptions }, { name: "jobTitle", label: "Job title", type: "text" }, { name: "reason", label: "Reason", type: "textarea", required: true }]} initial={{ status: "ACTIVE" }} />} />
  <section className="nesto-card p-5"><Table flush aria-label="Memberships"><TableHead><TableRow><TableHeaderCell>Person</TableHeaderCell><TableHeaderCell>Parent Group</TableHeaderCell><TableHeaderCell>Company</TableHeaderCell><TableHeaderCell>Role</TableHeaderCell><TableHeaderCell>Department</TableHeaderCell><TableHeaderCell>Status</TableHeaderCell><TableHeaderCell /></TableRow></TableHead><TableBody>{memberships.map((row) => <TableRow key={row.id}><TableCell><span className="font-medium text-fg">{row.user.firstName} {row.user.lastName}</span><p className="font-mono text-micro text-fg-subtle">{row.user.username}</p></TableCell><TableCell>{row.company.parentGroup.name}</TableCell><TableCell>{row.company.name}</TableCell><TableCell>{row.role.name}</TableCell><TableCell>{row.department?.name ?? "—"}</TableCell><TableCell><Badge tone={row.status === "ACTIVE" ? "success" : "danger"}>{row.status}</Badge></TableCell><TableCell><PlatformCommandButton label="Edit" title="Edit membership" action="membership.update" fixed={{ membershipId: row.id }} fields={[{ name: "roleKey", label: "Role", type: "select", required: true, options: roleOptions }, { name: "status", label: "Status", type: "select", required: true, options: statusOptions }, { name: "reason", label: "Reason", type: "textarea", required: true }]} initial={{ roleKey: row.role.key, status: row.status }} success="Membership updated." /></TableCell></TableRow>)}</TableBody></Table></section></div>;
}
