"use client";

import * as React from "react";
import { useRouter } from "next/navigation";
import { Building2, ChevronRight, Layers3, Plus, Trash2 } from "lucide-react";

import { engineeringApi, failureMessage } from "@/components/engineering/engineering-api";
import { selectClass } from "@/components/forms/record-form";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/components/ui/toast";

type Unit = { id: string; floorId: string; unitCode: string; name: string | null; unitTypeId: string; internalArea: string | null; saleableArea: string | null; rooms: number | null; bedrooms: number | null; bathrooms: number | null; description: string | null; isActive: boolean; version: number; publicationStatus: string; commercialProfile: { status: string } | null; _count: { threeDMeshBindings: number } };
type Floor = { id: string; buildingId: string; number: number | null; name: string; levelType: string; elevation: string | null; description: string | null; isActive: boolean; version: number; units: Unit[] };
type Building = { id: string; name: string; code: string | null; description: string | null; isActive: boolean; version: number; floors: Floor[] };
type UnitType = { id: string; name: string; code: string; category: string };
export type PlatformProjectStructure = { project: { id: string; name: string }; unitTypes: UnitType[]; buildings: Building[] };
type Selection = { kind: "building" | "floor" | "unit"; id: string };
type CreateKind = "building" | "floor" | "unit";

const LEVEL_TYPES = ["BASEMENT", "GROUND", "STANDARD", "MEZZANINE", "TECHNICAL", "ROOF", "OTHER"];

export function ProjectStructureManager({ projectId, structure }: { projectId: string; structure: PlatformProjectStructure }) {
  const [selection, setSelection] = React.useState<Selection | null>(null);
  const [createKind, setCreateKind] = React.useState<CreateKind>("building");
  const [pending, setPending] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);
  const router = useRouter();
  const toast = useToast();
  const floors = structure.buildings.flatMap((building) => building.floors.map((floor) => ({ ...floor, buildingName: building.name })));
  const units = floors.flatMap((floor) => floor.units);
  const selected = selection?.kind === "building" ? structure.buildings.find((row) => row.id === selection.id) : selection?.kind === "floor" ? floors.find((row) => row.id === selection.id) : units.find((row) => row.id === selection?.id);

  async function execute<T>(action: () => Promise<T>, message: string) {
    setPending(true); setError(null);
    try { await action(); toast({ title: message, tone: "success" }); router.refresh(); }
    catch (failure) { setError(failureMessage(failure, "The structure could not be changed.")); }
    finally { setPending(false); }
  }

  async function remove(kind: Selection["kind"], id: string, label: string, reason: string) {
    if (reason.trim().length < 3) return setError("Give a reason for this deletion.");
    if (!window.confirm(`Delete ${label}? This is allowed only when nothing depends on it.`)) return;
    await execute(() => engineeringApi(`/api/platform/3d/projects/${projectId}/structure/${kind}/${id}`, { method: "DELETE", body: { reason } }), `${label} deleted.`);
    setSelection(null);
  }

  return <div className="space-y-5">
    <section className="grid gap-4 md:grid-cols-3"><Metric label="Buildings" value={structure.buildings.length} /><Metric label="Floors" value={floors.length} /><Metric label="Units" value={units.length} /></section>
    <section className="nesto-card p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-card font-semibold text-fg">Create canonical structure</h2><p className="mt-1 text-table text-fg-muted">Changes are immediately available to Company Project pages and Unit Binding.</p></div><div className="flex rounded-lg border border-line p-1">{(["building", "floor", "unit"] as const).map((kind) => <button type="button" key={kind} onClick={() => setCreateKind(kind)} className={`rounded-md px-3 py-1.5 text-table font-medium capitalize ${createKind === kind ? "bg-accent-soft text-accent-strong" : "text-fg-muted hover:bg-hover"}`}><Plus className="mr-1 inline size-3.5" />{kind}</button>)}</div></div><div className="mt-4">{createKind === "building" ? <CreateBuilding projectId={projectId} execute={execute} pending={pending} /> : createKind === "floor" ? <CreateFloor projectId={projectId} buildings={structure.buildings} execute={execute} pending={pending} /> : <CreateUnit projectId={projectId} floors={floors} unitTypes={structure.unitTypes} execute={execute} pending={pending} />}</div>{error ? <p role="alert" className="mt-4 rounded-lg bg-danger-soft px-3 py-2 text-table text-danger-strong">{error}</p> : null}</section>

    <div className="grid gap-5 xl:grid-cols-[minmax(360px,0.85fr)_minmax(0,1.15fr)]">
      <section className="nesto-card overflow-hidden"><div className="border-b border-line px-5 py-4"><h2 className="text-card font-semibold text-fg">Structure tree</h2><p className="mt-1 text-table text-fg-muted">Select a record to edit, move, deactivate, or safely delete it.</p></div><div className="max-h-[720px] overflow-auto p-3">{structure.buildings.map((building) => <div key={building.id} className="mb-2 rounded-lg border border-line"><TreeButton active={selection?.kind === "building" && selection.id === building.id} onClick={() => setSelection({ kind: "building", id: building.id })} icon={<Building2 />} label={building.name} meta={`${building.floors.length} floors`} inactive={!building.isActive} />{building.floors.map((floor) => <div key={floor.id} className="border-t border-line pl-5"><TreeButton active={selection?.kind === "floor" && selection.id === floor.id} onClick={() => setSelection({ kind: "floor", id: floor.id })} icon={<Layers3 />} label={floor.name} meta={`${floor.units.length} units`} inactive={!floor.isActive} />{floor.units.map((unit) => <div key={unit.id} className="border-t border-line pl-6"><TreeButton active={selection?.kind === "unit" && selection.id === unit.id} onClick={() => setSelection({ kind: "unit", id: unit.id })} icon={<ChevronRight />} label={unit.unitCode} meta={unit.commercialProfile?.status ?? unit.publicationStatus} inactive={!unit.isActive} /></div>)}</div>)}</div>)}{structure.buildings.length === 0 ? <p className="p-8 text-center text-body text-fg-muted">Add a Building to begin the canonical hierarchy.</p> : null}</div></section>
      <section>{selection && selected ? <RecordEditor key={`${selection.kind}-${selection.id}-${selected.version}`} projectId={projectId} selection={selection} row={selected} buildings={structure.buildings} floors={floors} unitTypes={structure.unitTypes} execute={execute} remove={remove} pending={pending} /> : <div className="nesto-card flex min-h-64 items-center justify-center p-8 text-center text-body text-fg-muted">Select a Building, Floor, or Unit from the tree.</div>}</section>
    </div>
  </div>;
}

function CreateBuilding({ projectId, execute, pending }: FormProps) {
  const [name, setName] = React.useState(""); const [code, setCode] = React.useState(""); const [reason, setReason] = React.useState("");
  return <div className="grid gap-3 md:grid-cols-4"><Input value={name} onChange={(event) => setName(event.target.value)} placeholder="Building name" /><Input value={code} onChange={(event) => setCode(event.target.value)} placeholder="Code (optional)" /><Input value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Reason" /><Button disabled={pending || !name} onClick={() => void execute(() => engineeringApi(`/api/platform/3d/projects/${projectId}/structure`, { body: { action: "building.create", name, code: code || null, description: null, reason } }), "Building created.")}>Create building</Button></div>;
}

function CreateFloor({ projectId, buildings, execute, pending }: FormProps & { buildings: Building[] }) {
  const [buildingId, setBuildingId] = React.useState(buildings[0]?.id ?? ""); const [bulk, setBulk] = React.useState(false); const [number, setNumber] = React.useState("0"); const [name, setName] = React.useState("Ground Floor"); const [levelType, setLevelType] = React.useState("GROUND"); const [to, setTo] = React.useState("10"); const [reason, setReason] = React.useState("");
  const body = bulk ? { action: "floor.bulk", buildingId, from: Number(number), to: Number(to), reason } : { action: "floor.create", buildingId, number: number === "" ? null : Number(number), name, levelType, elevation: null, description: null, reason };
  return <div className="space-y-3"><label className="flex items-center gap-2 text-table text-fg-muted"><input type="checkbox" checked={bulk} onChange={(event) => setBulk(event.target.checked)} />Create a numbered range</label><div className="grid gap-3 md:grid-cols-3 xl:grid-cols-6"><select className={selectClass} value={buildingId} onChange={(event) => setBuildingId(event.target.value)}><option value="">Choose building</option>{buildings.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select><Input type="number" value={number} onChange={(event) => setNumber(event.target.value)} placeholder={bulk ? "From" : "Number"} />{bulk ? <Input type="number" value={to} onChange={(event) => setTo(event.target.value)} placeholder="To" /> : <><Input value={name} onChange={(event) => setName(event.target.value)} placeholder="Floor name" /><select className={selectClass} value={levelType} onChange={(event) => setLevelType(event.target.value)}>{LEVEL_TYPES.map((value) => <option key={value}>{value}</option>)}</select></>}<Input value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Reason" /><Button disabled={pending || !buildingId || (!bulk && !name)} onClick={() => void execute(() => engineeringApi(`/api/platform/3d/projects/${projectId}/structure`, { body }), bulk ? "Floors created." : "Floor created.")}>{bulk ? "Create floors" : "Create floor"}</Button></div></div>;
}

function CreateUnit({ projectId, floors, unitTypes, execute, pending }: FormProps & { floors: Array<Floor & { buildingName: string }>; unitTypes: UnitType[] }) {
  const [floorId, setFloorId] = React.useState(floors[0]?.id ?? ""); const [unitTypeId, setUnitTypeId] = React.useState(unitTypes[0]?.id ?? ""); const [bulk, setBulk] = React.useState(false); const [unitCode, setUnitCode] = React.useState(""); const [prefix, setPrefix] = React.useState("A-"); const [start, setStart] = React.useState("101"); const [end, setEnd] = React.useState("110"); const [reason, setReason] = React.useState("");
  const common = { floorId, unitTypeId, internalArea: null, saleableArea: null, rooms: null, bedrooms: null, bathrooms: null, description: null, reason };
  const body = bulk ? { action: "unit.bulk", ...common, prefix, start: Number(start), end: Number(end), padding: Math.max(start.length, 1), suffix: "" } : { action: "unit.create", ...common, unitCode, name: null };
  return <div className="space-y-3"><label className="flex items-center gap-2 text-table text-fg-muted"><input type="checkbox" checked={bulk} onChange={(event) => setBulk(event.target.checked)} />Generate a code range</label><div className="grid gap-3 md:grid-cols-3 xl:grid-cols-6"><select className={selectClass} value={floorId} onChange={(event) => setFloorId(event.target.value)}><option value="">Choose floor</option>{floors.map((row) => <option key={row.id} value={row.id}>{row.buildingName} · {row.name}</option>)}</select><select className={selectClass} value={unitTypeId} onChange={(event) => setUnitTypeId(event.target.value)}><option value="">Choose type</option>{unitTypes.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select>{bulk ? <><Input value={prefix} onChange={(event) => setPrefix(event.target.value)} placeholder="Prefix" /><div className="flex gap-2"><Input type="number" value={start} onChange={(event) => setStart(event.target.value)} placeholder="Start" /><Input type="number" value={end} onChange={(event) => setEnd(event.target.value)} placeholder="End" /></div></> : <Input value={unitCode} onChange={(event) => setUnitCode(event.target.value)} placeholder="Unit code" />}<Input value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Reason" /><Button disabled={pending || !floorId || !unitTypeId || (!bulk && !unitCode)} onClick={() => void execute(() => engineeringApi(`/api/platform/3d/projects/${projectId}/structure`, { body }), bulk ? "Units created." : "Unit created.")}>{bulk ? "Create units" : "Create unit"}</Button></div></div>;
}

type FormProps = { projectId: string; execute: <T>(action: () => Promise<T>, message: string) => Promise<void>; pending: boolean };

function RecordEditor({ projectId, selection, row, buildings, floors, unitTypes, execute, remove, pending }: { projectId: string; selection: Selection; row: Building | (Floor & { buildingName: string }) | Unit; buildings: Building[]; floors: Array<Floor & { buildingName: string }>; unitTypes: UnitType[]; execute: FormProps["execute"]; remove: (kind: Selection["kind"], id: string, label: string, reason: string) => Promise<void>; pending: boolean }) {
  const [reason, setReason] = React.useState("");
  if (selection.kind === "building") return <BuildingEditor projectId={projectId} row={row as Building} reason={reason} setReason={setReason} execute={execute} remove={remove} pending={pending} />;
  if (selection.kind === "floor") return <FloorEditor projectId={projectId} row={row as Floor} buildings={buildings} reason={reason} setReason={setReason} execute={execute} remove={remove} pending={pending} />;
  return <UnitEditor projectId={projectId} row={row as Unit} floors={floors} unitTypes={unitTypes} reason={reason} setReason={setReason} execute={execute} remove={remove} pending={pending} />;
}

type EditorProps<T> = { projectId: string; row: T; reason: string; setReason: (value: string) => void; execute: FormProps["execute"]; remove: (kind: Selection["kind"], id: string, label: string, reason: string) => Promise<void>; pending: boolean };

function BuildingEditor({ projectId, row, reason, setReason, execute, remove, pending }: EditorProps<Building>) {
  const [name, setName] = React.useState(row.name); const [code, setCode] = React.useState(row.code ?? ""); const [description, setDescription] = React.useState(row.description ?? ""); const [isActive, setActive] = React.useState(row.isActive);
  return <EditorFrame title={row.name} kind="Building" reason={reason} setReason={setReason} onDelete={() => remove("building", row.id, row.name, reason)} pending={pending}><Field label="Name"><Input value={name} onChange={(e) => setName(e.target.value)} /></Field><Field label="Code"><Input value={code} onChange={(e) => setCode(e.target.value)} /></Field><Field label="Description"><Textarea value={description} onChange={(e) => setDescription(e.target.value)} /></Field><Active checked={isActive} onChange={setActive} /><Button disabled={pending || reason.trim().length < 3} onClick={() => void execute(() => engineeringApi(`/api/platform/3d/projects/${projectId}/structure/building/${row.id}`, { method: "PATCH", body: { name, code: code || null, description: description || null, isActive, expectedVersion: row.version, reason } }), "Building saved.")}>Save building</Button></EditorFrame>;
}

function FloorEditor({ projectId, row, buildings, reason, setReason, execute, remove, pending }: EditorProps<Floor> & { buildings: Building[] }) {
  const [buildingId, setBuildingId] = React.useState(row.buildingId); const [number, setNumber] = React.useState(row.number?.toString() ?? ""); const [name, setName] = React.useState(row.name); const [levelType, setLevelType] = React.useState(row.levelType); const [elevation, setElevation] = React.useState(row.elevation ?? ""); const [description, setDescription] = React.useState(row.description ?? ""); const [isActive, setActive] = React.useState(row.isActive);
  return <EditorFrame title={row.name} kind="Floor" reason={reason} setReason={setReason} onDelete={() => remove("floor", row.id, row.name, reason)} pending={pending}><Field label="Building"><select className={selectClass} value={buildingId} onChange={(e) => setBuildingId(e.target.value)}>{buildings.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><div className="grid grid-cols-2 gap-3"><Field label="Number"><Input type="number" value={number} onChange={(e) => setNumber(e.target.value)} /></Field><Field label="Level type"><select className={selectClass} value={levelType} onChange={(e) => setLevelType(e.target.value)}>{LEVEL_TYPES.map((value) => <option key={value}>{value}</option>)}</select></Field></div><Field label="Name"><Input value={name} onChange={(e) => setName(e.target.value)} /></Field><Field label="Elevation"><Input value={elevation} onChange={(e) => setElevation(e.target.value)} /></Field><Field label="Description"><Textarea value={description} onChange={(e) => setDescription(e.target.value)} /></Field><Active checked={isActive} onChange={setActive} /><Button disabled={pending || reason.trim().length < 3} onClick={() => void execute(() => engineeringApi(`/api/platform/3d/projects/${projectId}/structure/floor/${row.id}`, { method: "PATCH", body: { buildingId, number: number === "" ? null : Number(number), name, levelType, elevation: elevation || null, description: description || null, isActive, expectedVersion: row.version, reason } }), "Floor saved.")}>Save floor</Button></EditorFrame>;
}

function UnitEditor({ projectId, row, floors, unitTypes, reason, setReason, execute, remove, pending }: EditorProps<Unit> & { floors: Array<Floor & { buildingName: string }>; unitTypes: UnitType[] }) {
  const [floorId, setFloorId] = React.useState(row.floorId); const [unitCode, setUnitCode] = React.useState(row.unitCode); const [name, setName] = React.useState(row.name ?? ""); const [unitTypeId, setUnitTypeId] = React.useState(row.unitTypeId); const [internalArea, setInternalArea] = React.useState(row.internalArea ?? ""); const [saleableArea, setSaleableArea] = React.useState(row.saleableArea ?? ""); const [isActive, setActive] = React.useState(row.isActive);
  return <EditorFrame title={row.unitCode} kind="Unit" reason={reason} setReason={setReason} onDelete={() => remove("unit", row.id, row.unitCode, reason)} pending={pending}><div className="flex flex-wrap gap-2"><Badge tone="neutral">{row.publicationStatus}</Badge>{row.commercialProfile ? <Badge tone="info">{row.commercialProfile.status}</Badge> : null}{row._count.threeDMeshBindings ? <Badge tone="success">{row._count.threeDMeshBindings} 3D link</Badge> : null}</div><Field label="Floor"><select className={selectClass} value={floorId} onChange={(e) => setFloorId(e.target.value)}>{floors.map((item) => <option key={item.id} value={item.id}>{item.buildingName} · {item.name}</option>)}</select></Field><div className="grid grid-cols-2 gap-3"><Field label="Unit code"><Input value={unitCode} onChange={(e) => setUnitCode(e.target.value)} /></Field><Field label="Name"><Input value={name} onChange={(e) => setName(e.target.value)} /></Field></div><Field label="Unit type"><select className={selectClass} value={unitTypeId} onChange={(e) => setUnitTypeId(e.target.value)}>{unitTypes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><div className="grid grid-cols-2 gap-3"><Field label="Internal m²"><Input value={internalArea} onChange={(e) => setInternalArea(e.target.value)} /></Field><Field label="Saleable m²"><Input value={saleableArea} onChange={(e) => setSaleableArea(e.target.value)} /></Field></div><Active checked={isActive} onChange={setActive} /><Button disabled={pending || reason.trim().length < 3} onClick={() => void execute(() => engineeringApi(`/api/platform/3d/projects/${projectId}/structure/unit/${row.id}`, { method: "PATCH", body: { floorId, unitCode, name: name || null, unitTypeId, internalArea: internalArea || null, saleableArea: saleableArea || null, rooms: row.rooms, bedrooms: row.bedrooms, bathrooms: row.bathrooms, description: row.description, isActive, expectedVersion: row.version, reason } }), "Unit saved.")}>Save unit</Button></EditorFrame>;
}

function EditorFrame({ title, kind, reason, setReason, onDelete, pending, children }: { title: string; kind: string; reason: string; setReason: (value: string) => void; onDelete: () => Promise<void>; pending: boolean; children: React.ReactNode }) {
  return <div className="nesto-card p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-meta uppercase tracking-wide text-fg-subtle">{kind}</p><h2 className="text-card font-semibold text-fg">{title}</h2></div><Button type="button" size="sm" variant="danger" onClick={() => void onDelete()} disabled={pending}><Trash2 />Delete</Button></div><div className="mt-5 space-y-4">{children}<Field label="Reason"><Input value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Why this structure is changing" /></Field></div></div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-meta font-medium text-fg-muted"><span className="mb-1.5 block">{label}</span>{children}</label>; }
function Active({ checked, onChange }: { checked: boolean; onChange: (value: boolean) => void }) { return <label className="flex items-center gap-2 text-body text-fg"><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} />Active</label>; }
function Metric({ label, value }: { label: string; value: number }) { return <div className="nesto-card p-5"><p className="text-table text-fg-muted">{label}</p><p className="mt-1 text-3xl font-semibold tabular-nums text-fg">{value}</p></div>; }
function TreeButton({ active, onClick, icon, label, meta, inactive }: { active: boolean; onClick: () => void; icon: React.ReactNode; label: string; meta: string; inactive: boolean }) { return <button type="button" onClick={onClick} className={`flex w-full items-center gap-2 px-3 py-2.5 text-left ${active ? "bg-accent-soft text-accent-strong" : "text-fg hover:bg-hover"}`}><span className="[&_svg]:size-4">{icon}</span><span className="min-w-0 flex-1 truncate text-table font-medium">{label}</span>{inactive ? <Badge tone="neutral">INACTIVE</Badge> : null}<span className="text-meta text-fg-subtle">{meta}</span></button>; }
