import {
  Circle,
  ArrowDownLeft,
  ArrowLeftRight,
  ArrowUpRight,
  BellRing,
  Boxes,
  Building2,
  CalendarCheck,
  CalendarClock,
  ChartPie,
  CircleCheckBig,
  ClipboardCheck,
  ClipboardList,
  CreditCard,
  Database,
  Eye,
  FileBadge,
  FilePlus,
  FileQuestionMark,
  FileSignal,
  FileStack,
  FileText,
  FileX,
  Flag,
  FlaskConical,
  FolderKanban,
  Gauge,
  Gavel,
  IdCard,
  Landmark,
  Laptop,
  LayoutDashboard,
  LifeBuoy,
  ListChecks,
  MessageCircleQuestionMark,
  MonitorSmartphone,
  Package,
  PackageCheck,
  PackageMinus,
  PenLine,
  PencilRuler,
  Plane,
  Plus,
  ReceiptText,
  RefreshCw,
  RotateCcw,
  Scale,
  Send,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Stamp,
  Target,
  ToggleRight,
  TrendingUp,
  TriangleAlert,
  Truck,
  Upload,
  UserCheck,
  UserPlus,
  Users,
  UsersRound,
  Wallet,
  type LucideIcon,
} from "lucide-react";

/**
 * Explicit icon registry.
 *
 * config/modules.ts and config/dashboards.ts store icon *names* so they stay
 * edge-safe and serialisable; this map turns a name into a component. Keeping
 * it explicit means the bundle only contains icons NESTO actually uses.
 */
const registry: Record<string, LucideIcon> = {
  ArrowDownLeft,
  ArrowLeftRight,
  ArrowUpRight,
  BellRing,
  Boxes,
  Building2,
  CalendarCheck,
  CalendarClock,
  ChartPie,
  CircleCheckBig,
  ClipboardCheck,
  ClipboardList,
  CreditCard,
  Database,
  Eye,
  FileBadge,
  FilePlus,
  FileQuestionMark,
  FileSignal,
  FileStack,
  FileText,
  FileX,
  Flag,
  FlaskConical,
  FolderKanban,
  Gauge,
  Gavel,
  IdCard,
  Landmark,
  Laptop,
  LayoutDashboard,
  LifeBuoy,
  ListChecks,
  MessageCircleQuestionMark,
  MonitorSmartphone,
  Package,
  PackageCheck,
  PackageMinus,
  PenLine,
  PencilRuler,
  Plane,
  Plus,
  ReceiptText,
  RefreshCw,
  RotateCcw,
  Scale,
  Send,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Stamp,
  Target,
  ToggleRight,
  TrendingUp,
  TriangleAlert,
  Truck,
  Upload,
  UserCheck,
  UserPlus,
  Users,
  UsersRound,
  Wallet,
};

export function getIcon(name: string): LucideIcon {
  return registry[name] ?? Circle;
}

export type { LucideIcon };
