"use client";

import * as React from "react";
import { CheckCircle2, XCircle } from "lucide-react";

import { useTranslations } from "@/components/i18n/i18n-provider";
import { enumLabel } from "@/lib/i18n/modules/adminAccess/enum-label";
import { engineeringApi } from "@/components/engineering/engineering-api";
import { Button } from "@/components/ui/button";
import { selectClass } from "@/components/forms/record-form";
import { FormSelect } from "@/components/ui/form-select";

type Option = { value: string; label: string };
type Result = { result: "ALLOW" | "DENY"; reason: string; permission: string; moduleKey: string | null; traces: Array<{ label: string; value: string; pass: boolean }> };

export function AccessInspector({ users, companies, projects, permissions }: { users: Option[]; companies: Option[]; projects: Array<Option & { companyId: string }>; permissions: Option[] }) {
  const t = useTranslations("adminAccess");
  const [userId, setUserId] = React.useState(users[0]?.value ?? ""); const [companyId, setCompanyId] = React.useState(companies[0]?.value ?? ""); const [projectId, setProjectId] = React.useState(""); const [permission, setPermission] = React.useState(permissions[0]?.value ?? ""); const [result, setResult] = React.useState<Result | null>(null); const [pending, setPending] = React.useState(false); const [error, setError] = React.useState<string | null>(null);
  const visibleProjects = projects.filter((project) => project.companyId === companyId);
  async function inspect(event: React.FormEvent) { event.preventDefault(); setPending(true); setError(null); try { const response = await engineeringApi<Result>("/api/platform-admin/command", { body: { action: "access.inspect", userId, companyId, ...(projectId ? { projectId } : {}), permission } }); setResult(response); } catch (failure) { setError(failure instanceof Error ? failure.message : t("users.inspector.error")); } finally { setPending(false); } }
  return <div className="grid gap-5 xl:grid-cols-[420px_1fr]"><form onSubmit={inspect} className="nesto-card space-y-4 p-5"><h2 className="text-card font-semibold text-fg">{t("users.inspector.decisionInput")}</h2>{[["user", t("users.inspector.user"), userId, setUserId, users], ["company", t("users.inspector.company"), companyId, (value: string) => { setCompanyId(value); setProjectId(""); }, companies], ["project", t("users.inspector.projectOptional"), projectId, setProjectId, visibleProjects], ["permission", t("users.inspector.permission"), permission, setPermission, permissions]].map(([id, label, value, set, options]) => <label key={id as string} className="block text-meta font-medium text-fg-muted">{label as string}<FormSelect className={`${selectClass} mt-1 w-full`} value={value as string} onChange={(event) => (set as (value: string) => void)(event.target.value)}>{id === "project" ? <option value="">{t("users.inspector.noProject")}</option> : null}{(options as Option[]).map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</FormSelect></label>)}{error ? <p role="alert" className="text-table text-danger-strong">{error}</p> : null}<Button type="submit" disabled={pending || !userId || !companyId || !permission} className="w-full">{pending ? t("users.inspector.resolving") : t("users.inspector.inspect")}</Button></form>
    <section className="nesto-card p-5">{result ? <><div className="flex items-center gap-3 border-b border-line pb-4">{result.result === "ALLOW" ? <CheckCircle2 className="size-8 text-success-strong" /> : <XCircle className="size-8 text-danger-strong" />}<div><p className={`text-xl font-semibold ${result.result === "ALLOW" ? "text-success-strong" : "text-danger-strong"}`}>{enumLabel(t, "enums.decision", result.result)}</p><p className="text-table text-fg-muted">{result.reason}</p></div></div><dl className="mt-4 divide-y divide-line">{result.traces.map((trace) => <div key={trace.label} className="grid grid-cols-[minmax(0,1fr)_auto] gap-x-4 gap-y-1 py-3 text-table sm:grid-cols-[160px_minmax(0,1fr)_auto] sm:gap-y-0">{/* Phones: label and verdict on one line, the value under them at full width (AUD-04 §3, D-09-19, MW-01). */}<dt className="font-medium text-fg-muted max-sm:col-start-1 max-sm:row-start-1">{trace.label}</dt><dd className="min-w-0 text-fg [overflow-wrap:anywhere] max-sm:col-span-2 max-sm:row-start-2">{trace.value}</dd><dd className={`${trace.pass ? "text-success-strong" : "text-danger-strong"} max-sm:col-start-2 max-sm:row-start-1`}>{enumLabel(t, "enums.decision", trace.pass ? "PASS" : "FAIL")}</dd></div>)}</dl></> : <div className="grid min-h-64 place-items-center text-center"><div><SearchIcon /><h2 className="mt-3 text-card font-semibold text-fg">{t("users.inspector.emptyTitle")}</h2><p className="mt-1 text-table text-fg-muted">{t("users.inspector.emptyBody")}</p></div></div>}</section></div>;
}

function SearchIcon() { return <span className="mx-auto grid size-12 place-items-center rounded-xl bg-accent-soft text-xl text-accent-strong">?</span>; }
