import { getTranslations } from "@/lib/i18n/server";
import { enumLabel } from "@/lib/i18n/modules/adminAccess/enum-label";
import { Badge } from "@/components/ui/badge";
import { PlatformCommandButton } from "@/components/platform/platform-command";
import { Card } from "@/components/ui/card";
import { PageHeader } from "@/components/ui/page-header";
import { requirePlatformContext } from "@/lib/context/platform-context";
import { platformDiagnostics } from "@/lib/modules/platform/platform-control.query";
export async function generateMetadata() { const t = await getTranslations("adminPlatform"); return { title: t("system.diagnostics.metaTitle") }; }
export default async function DataDiagnosticsPage() { const t = await getTranslations("adminPlatform"); const context = await requirePlatformContext(); const findings = await platformDiagnostics(context); return <div className="space-y-5"><PageHeader title={t("system.diagnostics.title")} description={t("system.diagnostics.description")} /><Card className="divide-y divide-line">{findings.map((finding) => <div key={finding.key} className="p-5"><div className="flex items-center justify-between gap-4"><div><h2 className="text-body font-medium text-fg">{enumLabel(t, "system.diagnostics.labels", finding.key, finding.label)}</h2><p className="text-meta text-fg-subtle">{t("system.diagnostics.diagnostic", { key: finding.key })}</p></div><Badge tone={finding.count === 0 ? "success" : finding.severity === "CRITICAL" ? "danger" : "warning"}>{finding.count === 0 ? t("system.diagnostics.clear") : t("system.diagnostics.found", { count: finding.count })}</Badge></div>{"items" in finding && finding.items?.length ? <div className="mt-3 space-y-2">{finding.items.map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-line px-3 py-2"><span className="text-table text-fg">{item.label} <span className="text-fg-subtle">({item.status})</span></span><PlatformCommandButton label={t("system.diagnostics.repair")} title={t("system.diagnostics.repairTitle")} description={t("system.diagnostics.repairDescription")} action="membership.repair" fixed={{ membershipId: item.id }} reasonOnly destructive success={t("system.diagnostics.repairSuccess")} /></div>)}</div> : null}</div>)}</Card></div>; }
