import { getTranslations } from "@/lib/i18n/server";
import { enumLabel } from "@/lib/i18n/modules/adminAccess/enum-label";
import { PlatformCommandButton } from "@/components/platform/platform-command";
import { Badge } from "@/components/ui/badge";
import { PageHeader } from "@/components/ui/page-header";
import { requirePlatformContext } from "@/lib/context/platform-context";
import { listFeatureFlags, listPlatformCompanies, listPlatformUsers } from "@/lib/modules/platform/platform-control.query";
import { listParentGroups } from "@/lib/modules/platform/platform.service";

export async function generateMetadata() { const t = await getTranslations("adminPlatform"); return { title: t("system.featureFlags.metaTitle") }; }
const stateTone = (state: string) => state === "ON" ? "success" as const : state === "BETA" ? "warning" as const : "neutral" as const;
export default async function FeatureFlagsPage() { const t = await getTranslations("adminPlatform"); const context = await requirePlatformContext(); const [flags, groups, companies, users] = await Promise.all([listFeatureFlags(context), listParentGroups(context), listPlatformCompanies(context), listPlatformUsers(context)]); const targetHint = t("system.featureFlags.targetHint", { groups: groups.slice(0, 3).map((row) => `${row.name}=${row.id}`).join("; "), companies: companies.slice(0, 3).map((row) => `${row.name}=${row.id}`).join("; ") }); return <div className="space-y-5"><PageHeader title={t("system.featureFlags.title")} description={t("system.featureFlags.description")} actions={<PlatformCommandButton label={t("system.featureFlags.create")} title={t("system.featureFlags.createTitle")} action="featureFlag.create" variant="primary" success={t("system.featureFlags.created")} fields={[{ name: "key", label: t("system.featureFlags.fields.key"), type: "text", required: true }, { name: "name", label: t("system.featureFlags.fields.name"), type: "text", required: true }, { name: "description", label: t("system.featureFlags.fields.description"), type: "textarea" }, { name: "defaultState", label: t("system.featureFlags.fields.defaultState"), type: "select", required: true, options: ["OFF", "ON", "BETA"].map((value) => ({ value, label: enumLabel(t, "enums.flagState", value) })) }, { name: "reason", label: t("system.featureFlags.fields.reason"), type: "textarea", required: true }]} initial={{ defaultState: "OFF" }} />} />
  <div className="grid gap-4 xl:grid-cols-2">{flags.map((flag) => <section key={flag.id} className="nesto-card p-5"><div className="flex items-start justify-between gap-4"><div><h2 className="text-card font-semibold text-fg">{flag.name}</h2><p className="font-mono text-meta text-fg-subtle">{flag.key}</p><p className="mt-2 text-table text-fg-muted">{flag.description ?? t("system.featureFlags.noDescription")}</p></div><Badge tone={stateTone(flag.defaultState)}>{enumLabel(t, "enums.flagState", flag.defaultState)}</Badge></div><div className="mt-4 space-y-2 border-t border-line pt-4">{flag.overrides.length ? flag.overrides.map((override) => <div key={override.id} className="flex items-center justify-between gap-3 text-table"><span>{enumLabel(t, "enums.flagScope", override.scopeType)} · <span className="font-mono text-meta">{override.scopeId}</span></span><Badge tone={stateTone(override.state)}>{enumLabel(t, "enums.flagState", override.state)}</Badge></div>) : <p className="text-table text-fg-subtle">{t("system.featureFlags.noOverrides")}</p>}</div><div className="mt-4"><PlatformCommandButton label={t("system.featureFlags.setOverride")} title={t("system.featureFlags.overrideTitle", { name: flag.name })} description={targetHint} action="featureFlag.override" fixed={{ flagId: flag.id }} fields={[{ name: "scopeType", label: t("system.featureFlags.fields.scopeType"), type: "select", required: true, options: ["PLATFORM", "GROUP", "COMPANY", "USER"].map((value) => ({ value, label: enumLabel(t, "enums.flagScope", value) })) }, { name: "scopeId", label: t("system.featureFlags.fields.targetId"), type: "text", required: true, hint: t("system.featureFlags.fields.targetHint", { count: users.length }) }, { name: "state", label: t("system.featureFlags.fields.state"), type: "select", required: true, options: ["OFF", "ON", "BETA"].map((value) => ({ value, label: enumLabel(t, "enums.flagState", value) })) }, { name: "reason", label: t("system.featureFlags.fields.reason"), type: "textarea", required: true }]} initial={{ scopeType: "PLATFORM", scopeId: "platform", state: flag.defaultState }} success={t("system.featureFlags.overrideSaved")} /></div></section>)}</div></div>; }
