import { PlatformCommandButton } from "@/components/platform/platform-command";
import { Badge } from "@/components/ui/badge";
import { PageHeader } from "@/components/ui/page-header";
import { Table, TableBody, TableCell, TableHead, TableHeaderCell, TableRow } from "@/components/ui/table";
import { requirePlatformContext } from "@/lib/context/platform-context";
import { listPlatformSessions } from "@/lib/modules/platform/platform-control.query";
import { getTranslations } from "@/lib/i18n/server";
import { enumLabel } from "@/lib/i18n/modules/adminAccess/enum-label";
import { formatDate } from "@/lib/utils/format";

export async function generateMetadata() { const t = await getTranslations("adminAccess"); return { title: t("users.sessions.metaTitle") }; }
export default async function SessionsPage() { const t = await getTranslations("adminAccess"); const context = await requirePlatformContext(); const sessions = await listPlatformSessions(context); return <div className="space-y-5"><PageHeader title={t("users.sessions.title")} description={t("users.sessions.description")} /><section className="nesto-card p-5"><Table stack aria-label={t("users.sessions.tableLabel")}><TableHead><TableRow><TableHeaderCell>{t("users.sessions.cols.user")}</TableHeaderCell><TableHeaderCell>{t("users.sessions.cols.company")}</TableHeaderCell><TableHeaderCell>{t("users.sessions.cols.device")}</TableHeaderCell><TableHeaderCell>{t("users.sessions.cols.ip")}</TableHeaderCell><TableHeaderCell>{t("users.sessions.cols.lastActive")}</TableHeaderCell><TableHeaderCell>{t("users.sessions.cols.expires")}</TableHeaderCell><TableHeaderCell>{t("users.sessions.cols.status")}</TableHeaderCell><TableHeaderCell /></TableRow></TableHead><TableBody>{sessions.map((session) => <TableRow key={session.id}><TableCell><span className="font-medium text-fg">{session.user.firstName} {session.user.lastName}</span><p className="font-mono text-micro text-fg-subtle">{session.user.username}</p></TableCell><TableCell>{session.company?.name ?? t("users.sessions.platform")}</TableCell><TableCell className="max-w-64 truncate" title={session.userAgent ?? undefined}>{session.userAgent ?? t("common.unknown")}</TableCell><TableCell className="font-mono text-meta">{session.ipAddress ?? "—"}</TableCell><TableCell>{formatDate(session.updatedAt)}</TableCell><TableCell>{formatDate(session.expiresAt)}</TableCell><TableCell><Badge tone={session.active ? "success" : "danger"}>{enumLabel(t, "enums.sessionState", session.active ? "ACTIVE" : "EXPIRED")}</Badge></TableCell><TableCell>{session.id === context.sessionId ? <span className="text-meta text-fg-subtle">{t("users.sessions.current")}</span> : <PlatformCommandButton label={t("common.revoke")} title={t("users.sessions.revokeTitle")} action="session.revoke" fixed={{ sessionId: session.id }} reasonOnly destructive variant="danger" success={t("users.sessions.revoked")} />}</TableCell></TableRow>)}</TableBody></Table></section></div>; }
