import { PlatformCommandButton } from "@/components/platform/platform-command";
import { Badge } from "@/components/ui/badge";
import { PageHeader } from "@/components/ui/page-header";
import { Table, TableBody, TableCell, TableHead, TableHeaderCell, TableRow } from "@/components/ui/table";
import { MODULE_KEYS, modules } from "@/config/modules";
import { requirePlatformContext } from "@/lib/context/platform-context";
import { listPlatformGrants, listPlatformUsers } from "@/lib/modules/platform/platform-control.query";
import { listParentGroups } from "@/lib/modules/platform/platform.service";
import { getTranslations } from "@/lib/i18n/server";
import { enumLabel } from "@/lib/i18n/modules/adminAccess/enum-label";
import { formatDate } from "@/lib/utils/format";

export async function generateMetadata() { const t = await getTranslations("adminAccess"); return { title: t("users.grants.metaTitle") }; }
export default async function GrantsPage() { const t = await getTranslations("adminAccess"); const context = await requirePlatformContext(); const [grants, users, groups] = await Promise.all([listPlatformGrants(context), listPlatformUsers(context), listParentGroups(context, { includeStandalone: true })]); return <div className="space-y-5"><PageHeader title={t("users.grants.title")} description={t("users.grants.description")} actions={<PlatformCommandButton label={t("users.grants.create")} title={t("users.grants.createTitle")} description={t("users.grants.createDescription")} action="grant.create" variant="primary" success={t("users.grants.success")} fields={[{ name: "userId", label: t("users.grants.fields.user"), type: "select", required: true, options: users.filter((row) => !row.platformAccess).map((row) => ({ value: row.id, label: `${row.firstName} ${row.lastName} (${row.username})` })) }, { name: "parentGroupId", label: t("users.grants.fields.parentGroup"), type: "select", required: true, options: groups.map((row) => ({ value: row.id, label: row.name })) }, { name: "moduleKey", label: t("users.grants.fields.module"), type: "select", required: true, options: MODULE_KEYS.map((value) => ({ value, label: modules[value].label })) }, { name: "scopeType", label: t("users.grants.fields.scope"), type: "select", required: true, options: ["GROUP", "COMPANY", "PROJECT"].map((value) => ({ value, label: enumLabel(t, "enums.scopeType", value) })) }, { name: "scopeId", label: t("users.grants.fields.scopeRecord"), type: "text", required: true, hint: t("users.grants.fields.scopeHint") }, { name: "accessLevel", label: t("users.grants.fields.accessLevel"), type: "select", required: true, options: ["VIEW", "CONTRIBUTE", "APPROVE", "MANAGE"].map((value) => ({ value, label: enumLabel(t, "enums.accessLevel", value) })) }, { name: "expiresAt", label: t("users.grants.fields.expires"), type: "date" }, { name: "reason", label: t("users.grants.fields.reason"), type: "textarea", required: true }]} />} />
  <section className="nesto-card p-5"><Table stack flush aria-label={t("users.grants.tableLabel")}><TableHead><TableRow><TableHeaderCell>{t("users.grants.cols.holder")}</TableHeaderCell><TableHeaderCell>{t("users.grants.cols.group")}</TableHeaderCell><TableHeaderCell>{t("users.grants.cols.module")}</TableHeaderCell><TableHeaderCell>{t("users.grants.cols.scope")}</TableHeaderCell><TableHeaderCell>{t("users.grants.cols.level")}</TableHeaderCell><TableHeaderCell>{t("users.grants.cols.expires")}</TableHeaderCell><TableHeaderCell>{t("users.grants.cols.status")}</TableHeaderCell><TableHeaderCell /></TableRow></TableHead><TableBody>{grants.map((grant) => { const live = !grant.revokedAt && (!grant.expiresAt || new Date(grant.expiresAt) > new Date()); return <TableRow key={grant.id}><TableCell><span className="font-medium text-fg">{grant.user.firstName} {grant.user.lastName}</span><p className="font-mono text-micro text-fg-subtle">{grant.user.username}</p></TableCell><TableCell>{grant.parentGroup.name}</TableCell><TableCell>{grant.functionKey ?? "—"}</TableCell><TableCell>{enumLabel(t, "enums.scopeType", grant.scopeType)}<p className="font-mono text-micro text-fg-subtle">{grant.scopeId}</p></TableCell><TableCell>{enumLabel(t, "enums.accessLevel", grant.accessLevel)}</TableCell><TableCell>{grant.expiresAt ? formatDate(grant.expiresAt) : t("users.grants.noExpiry")}</TableCell><TableCell><Badge tone={live ? "success" : "danger"}>{enumLabel(t, "enums.grantState", grant.revokedAt ? "REVOKED" : live ? "LIVE" : "EXPIRED")}</Badge></TableCell><TableCell>{live ? <PlatformCommandButton label={t("common.revoke")} title={t("users.grants.revokeTitle")} action="grant.revoke" fixed={{ grantId: grant.id }} reasonOnly destructive variant="danger" success={t("users.grants.revoked")} /> : null}</TableCell></TableRow>; })}</TableBody></Table></section></div>; }
