import { getTranslations } from "@/lib/i18n/server";
import { PlatformCommandButton } from "@/components/platform/platform-command";
import { Card } from "@/components/ui/card";
import { PageHeader } from "@/components/ui/page-header";
import { requirePlatformContext } from "@/lib/context/platform-context";
import { platformSettings } from "@/lib/modules/platform/platform-control.query";
import { systemOverview } from "@/lib/modules/platform/platform-system.service";

export async function generateMetadata() { const t = await getTranslations("adminPlatform"); return { title: t("system.index.metaTitle") }; }
const settings = [
  ["general.platformName", "platformName", "text"], ["general.platformUrl", "platformUrl", "text"], ["general.supportContact", "supportContact", "text"],
  ["localization.defaultLanguage", "defaultLanguage", "text"], ["localization.defaultCurrency", "defaultCurrency", "text"], ["localization.defaultTimezone", "defaultTimezone", "text"],
  ["branding.logoUrl", "logoUrl", "text"], ["branding.faviconUrl", "faviconUrl", "text"],
] as const;
export default async function SettingsPage() { const t = await getTranslations("adminPlatform"); const context = await requirePlatformContext(); const [data, overview] = await Promise.all([platformSettings(context), systemOverview(context)]); const groups = [{ id: "general", title: t("system.index.groups.general"), prefix: "general." }, { id: "localization", title: t("system.index.groups.localization"), prefix: "localization." }, { id: "branding", title: t("system.index.groups.branding"), prefix: "branding." }]; return <div className="space-y-5"><PageHeader title={t("system.index.title")} description={t("system.index.description")} /><Card className="p-5" data-testid="system-runtime"><h2 className="text-card font-semibold text-fg">{t("system.index.runtime")}</h2><p className="mt-1 text-table text-fg-muted">{t("system.index.runtimeNote")}</p><dl className="mt-3 grid gap-3 sm:grid-cols-3"><div><dt className="text-meta text-fg-subtle">{t("system.index.platformUrl")}</dt><dd className="break-all text-body text-fg">{overview.general.platformUrl}</dd></div><div><dt className="text-meta text-fg-subtle">{t("system.index.environment")}</dt><dd className="text-body text-fg">{overview.general.environment}</dd></div><div><dt className="text-meta text-fg-subtle">{t("system.index.version")}</dt><dd className="font-mono text-body text-fg">{overview.general.version}</dd></div></dl></Card><div className="grid gap-4 xl:grid-cols-3">{groups.map((group) => <Card key={group.id} className="p-5"><h2 className="text-card font-semibold text-fg">{group.title}</h2><div className="mt-4 divide-y divide-line">{settings.filter(([key]) => key.startsWith(group.prefix)).map(([key, labelKey, type]) => { const label = t(`system.index.settings.${labelKey}` as never); return <div key={key} className="flex items-center justify-between gap-4 py-3"><div><p className="text-table font-medium text-fg">{label}</p><p className="max-w-56 truncate font-mono text-meta text-fg-subtle">{String(data.values[key] ?? "—")}</p></div><PlatformCommandButton label={t("system.index.edit")} title={t("system.index.editTitle", { label: label.toLowerCase() })} action="setting.save" fixed={{ key }} fields={[{ name: "value", label, type, required: true }, { name: "reason", label: t("common.reason"), type: "textarea", required: true }]} initial={{ value: data.values[key] }} success={t("system.index.success")} /></div>; })}</div></Card>)}</div></div>; }
