import { PlatformCommandButton } from "@/components/platform/platform-command";
import { Badge } from "@/components/ui/badge";
import { PageHeader } from "@/components/ui/page-header";
import { Table, TableBody, TableCell, TableHead, TableHeaderCell, TableRow } from "@/components/ui/table";
import { requirePlatformContext } from "@/lib/context/platform-context";
import { listPlatformCompanies, listPlatformModules } from "@/lib/modules/platform/platform-control.query";

export const metadata = { title: "Modules" };
export default async function ModulesPage() { const context = await requirePlatformContext(); const [moduleRows, companies] = await Promise.all([listPlatformModules(context), listPlatformCompanies(context)]); return <div className="space-y-5"><PageHeader title="Module control" description="Company module enablement is combined with role permission at runtime. Disabling preserves all tenant records." actions={<PlatformCommandButton label="Set company module" title="Set company module" action="module.set" variant="primary" success="Module configuration changed." fields={[{ name: "companyId", label: "Company", type: "select", required: true, options: companies.map((row) => ({ value: row.id, label: `${row.parentGroup.name} · ${row.name}` })) }, { name: "moduleKey", label: "Module", type: "select", required: true, options: moduleRows.map((row) => ({ value: row.key, label: row.name })) }, { name: "enabled", label: "Enabled", type: "checkbox", hint: "Turn off only after reviewing dependent modules." }, { name: "reason", label: "Reason", type: "textarea", required: true }]} initial={{ enabled: true }} />} /><section className="nesto-card p-5"><Table flush aria-label="Module registry"><TableHead><TableRow><TableHeaderCell>Module</TableHeaderCell><TableHeaderCell>Key</TableHeaderCell><TableHeaderCell>Route</TableHeaderCell><TableHeaderCell>Registry</TableHeaderCell><TableHeaderCell>Enabled Companies</TableHeaderCell><TableHeaderCell>Status</TableHeaderCell></TableRow></TableHead><TableBody>{moduleRows.map((row) => <TableRow key={row.id}><TableCell><span className="font-medium text-fg">{row.name}</span><p className="text-meta text-fg-subtle">{row.description}</p></TableCell><TableCell className="font-mono text-meta">{row.key}</TableCell><TableCell className="font-mono text-meta">{row.route}</TableCell><TableCell><Badge tone={row.registry ? "success" : "danger"}>{row.registry ? "SYNCED" : "DB ONLY"}</Badge></TableCell><TableCell>{row.enabledCompanies} / {row.companies}</TableCell><TableCell><Badge tone={row.status === "ACTIVE" ? "success" : "danger"}>{row.status}</Badge></TableCell></TableRow>)}</TableBody></Table></section></div>; }
