import { PlatformCommandButton } from "@/components/platform/platform-command";
import { Badge } from "@/components/ui/badge";
import { PageHeader } from "@/components/ui/page-header";
import { requirePlatformContext } from "@/lib/context/platform-context";
import { listFeatureFlags, listPlatformCompanies, listPlatformUsers } from "@/lib/modules/platform/platform-control.query";
import { listParentGroups } from "@/lib/modules/platform/platform.service";

export const metadata = { title: "Feature Flags" };
const stateTone = (state: string) => state === "ON" ? "success" as const : state === "BETA" ? "warning" as const : "neutral" as const;
export default async function FeatureFlagsPage() { const context = await requirePlatformContext(); const [flags, groups, companies, users] = await Promise.all([listFeatureFlags(context), listParentGroups(context), listPlatformCompanies(context), listPlatformUsers(context)]); const targetHint = `Platform: platform. Groups: ${groups.slice(0, 3).map((row) => `${row.name}=${row.id}`).join("; ")}. Companies: ${companies.slice(0, 3).map((row) => `${row.name}=${row.id}`).join("; ")}.`; return <div className="space-y-5"><PageHeader title="Feature flags" description="Specific overrides win in the order User → Company → Group → Platform → Default." actions={<PlatformCommandButton label="Create flag" title="Create feature flag" action="featureFlag.create" variant="primary" success="Feature flag created." fields={[{ name: "key", label: "Flag key", type: "text", required: true }, { name: "name", label: "Name", type: "text", required: true }, { name: "description", label: "Description", type: "textarea" }, { name: "defaultState", label: "Default state", type: "select", required: true, options: ["OFF", "ON", "BETA"].map((value) => ({ value, label: value })) }, { name: "reason", label: "Reason", type: "textarea", required: true }]} initial={{ defaultState: "OFF" }} />} />
  <div className="grid gap-4 xl:grid-cols-2">{flags.map((flag) => <section key={flag.id} className="nesto-card p-5"><div className="flex items-start justify-between gap-4"><div><h2 className="text-card font-semibold text-fg">{flag.name}</h2><p className="font-mono text-meta text-fg-subtle">{flag.key}</p><p className="mt-2 text-table text-fg-muted">{flag.description ?? "No description"}</p></div><Badge tone={stateTone(flag.defaultState)}>{flag.defaultState}</Badge></div><div className="mt-4 space-y-2 border-t border-line pt-4">{flag.overrides.length ? flag.overrides.map((override) => <div key={override.id} className="flex items-center justify-between gap-3 text-table"><span>{override.scopeType} · <span className="font-mono text-meta">{override.scopeId}</span></span><Badge tone={stateTone(override.state)}>{override.state}</Badge></div>) : <p className="text-table text-fg-subtle">No overrides.</p>}</div><div className="mt-4"><PlatformCommandButton label="Set override" title={`Set ${flag.name} override`} description={targetHint} action="featureFlag.override" fixed={{ flagId: flag.id }} fields={[{ name: "scopeType", label: "Scope type", type: "select", required: true, options: ["PLATFORM", "GROUP", "COMPANY", "USER"].map((value) => ({ value, label: value })) }, { name: "scopeId", label: "Target ID", type: "text", required: true, hint: `Use platform for PLATFORM. ${users.length} user IDs are available from User Accounts.` }, { name: "state", label: "State", type: "select", required: true, options: ["OFF", "ON", "BETA"].map((value) => ({ value, label: value })) }, { name: "reason", label: "Reason", type: "textarea", required: true }]} initial={{ scopeType: "PLATFORM", scopeId: "platform", state: flag.defaultState }} success="Feature override saved." /></div></section>)}</div></div>; }
