import Link from "@/components/navigation/nav-link";
import { PlatformCommandButton } from "@/components/platform/platform-command";
import { Badge } from "@/components/ui/badge";
import { PageHeader } from "@/components/ui/page-header";
import { Table, TableBody, TableCell, TableHead, TableHeaderCell, TableRow } from "@/components/ui/table";
import { requirePlatformContext } from "@/lib/context/platform-context";
import { listPlatformUsers } from "@/lib/modules/platform/platform-control.query";
import { formatDate } from "@/lib/utils/format";

export const metadata = { title: "User Accounts" };
type Props = { searchParams: Promise<{ q?: string }> };

/** `?q=` narrows the accounts, so a search result lands on the person it named (Admin IA §17, §41). */
export default async function UsersPage({ searchParams }: Props) { const { q = "" } = await searchParams; const context = await requirePlatformContext(); const term = q.trim().toLowerCase(); const users = (await listPlatformUsers(context)).filter((user) => !term || [user.username, user.firstName, user.lastName, user.email ?? ""].some((value) => value.toLowerCase().includes(term))); return <div className="space-y-5"><PageHeader title="Users" description="Platform identities, login status, memberships and sessions." />{term ? <p className="text-table text-fg-muted">Showing accounts matching “{q}” · <Link href="/admin/users" className="text-accent-strong hover:underline">Show all</Link></p> : null}<section className="nesto-card p-5"><Table flush aria-label="User accounts"><TableHead><TableRow><TableHeaderCell>User</TableHeaderCell><TableHeaderCell>Group</TableHeaderCell><TableHeaderCell>Status</TableHeaderCell><TableHeaderCell>Memberships</TableHeaderCell><TableHeaderCell>Sessions</TableHeaderCell><TableHeaderCell>Last Login</TableHeaderCell><TableHeaderCell /></TableRow></TableHead><TableBody>{users.map((user) => <TableRow key={user.id}><TableCell><span className="font-medium text-fg">{user.firstName} {user.lastName}</span><p className="font-mono text-meta text-fg-subtle">{user.username}</p></TableCell><TableCell>{user.platformAccess ? <Badge tone="info">PLATFORM</Badge> : user.personProfile?.parentGroup.name ?? "—"}</TableCell><TableCell><Badge tone={user.status === "ACTIVE" ? "success" : "danger"}>{user.status}</Badge></TableCell><TableCell>{user._count.memberships}</TableCell><TableCell>{user._count.sessions}</TableCell><TableCell>{user.lastLoginAt ? formatDate(user.lastLoginAt) : "Never"}</TableCell><TableCell>{user.id !== context.userId ? <PlatformCommandButton label="Account status" title={`Change ${user.username} status`} description="Disabling or suspending an account immediately revokes all of its sessions." action="user.status" fixed={{ userId: user.id }} fields={[{ name: "status", label: "Status", type: "select", required: true, options: ["ACTIVE", "INACTIVE", "SUSPENDED"].map((value) => ({ value, label: value })) }, { name: "reason", label: "Reason", type: "textarea", required: true }]} initial={{ status: user.status }} success="User status changed." /> : <span className="text-meta text-fg-subtle">Current session</span>}</TableCell></TableRow>)}</TableBody></Table></section></div>; }
