ALTER TYPE "AuthEventType" ADD VALUE IF NOT EXISTS 'SESSION_EXPIRED';
ALTER TYPE "AuthEventType" ADD VALUE IF NOT EXISTS 'SESSION_REVOKED';
ALTER TYPE "AuthEventType" ADD VALUE IF NOT EXISTS 'IMPERSONATION_STARTED';
ALTER TYPE "AuthEventType" ADD VALUE IF NOT EXISTS 'IMPERSONATION_ENDED';
ALTER TYPE "AuthEventType" ADD VALUE IF NOT EXISTS 'USER_SWITCHED';
