/**
 * Role dashboard configuration (PRD #4 §57).
 *
 * A dashboard is a list of KPI keys, widget keys and quick-action keys — never
 * a page. Each entry is still checked against the user's own permissions when
 * it is resolved, so a configuration line can widen nothing (PRD #4 §10, §19).
 *
 * Because widgets are keyed rather than bound to role names, a future custom
 * role composes a dashboard from the same registry (PRD #4 §89).
 */
import type { RoleKey } from "./roles";

export type DashboardConfig = {
  /** A short line under the greeting, describing the role's focus. */
  focus: string;
  kpis: string[];
  widgets: string[];
  quickActions: string[];
};

export const dashboards: Record<RoleKey, DashboardConfig> = {
  OWNER: {
    focus: "Company-wide performance across every department.",
    kpis: ["activeProjects", "invoicedValue", "pipelineValue", "headcount"],
    widgets: [
      "attention",
      "announcements",
      "favorites",
      "recentWork",
      "upcomingMeetings",
      "pendingApprovals",
      "approvalBottlenecks",
      "activeProjects",
      "criticalMilestones",
      "engineeringBottlenecks",
      "contractorCompliance",
      "financeSummary",
      "salesPipeline",
      "workforce",
      "qualityRecords",
      "hseHazardsByRisk",
      "recentActivity",
    ],
    quickActions: ["newProject", "newClient", "newInvoice", "uploadDocument"],
  },
  ADMIN: {
    focus: "Platform administration: users, roles and company configuration.",
    kpis: ["teamSize", "enabledModuleCount", "openSupportCount", "documentCount"],
    widgets: [
      "attention",
      "announcements",
      "favorites",
      "recentWork",
      "userDirectory",
      "companyModules",
      "supportRequests",
      "recentDocuments",
      "recentActivity",
    ],
    quickActions: ["inviteUser", "uploadDocument"],
  },
  COMPANY_IT: {
    focus: "Accounts, access and platform support.",
    kpis: ["teamSize", "openSupportCount", "enabledModuleCount", "openTaskCount"],
    widgets: [
      "attention",
      "announcements",
      "favorites",
      "recentWork",
      "supportRequests",
      "teamDirectory",
      "companyModules",
      "recentActivity",
    ],
    quickActions: ["newSupportRequest"],
  },
  HR: {
    focus: "People operations, records and absence.",
    kpis: ["headcount", "pendingLeave", "openTaskCount", "activeProjects"],
    widgets: [
      "attention",
      "announcements",
      "favorites",
      "recentWork",
      "upcomingMeetings",
      "pendingApprovals",
      "leaveRequests",
      "workforce",
      "teamDirectory",
      "recentActivity",
    ],
    quickActions: ["requestLeave", "inviteUser", "uploadDocument"],
  },
  CEO: {
    focus: "Executive overview: performance, exposure and approvals.",
    kpis: ["activeProjects", "invoicedValue", "pipelineValue", "projectsAtRisk"],
    widgets: [
      "attention",
      "announcements",
      "favorites",
      "recentWork",
      "upcomingMeetings",
      "pendingApprovals",
      "approvalBottlenecks",
      "activeProjects",
      "criticalMilestones",
      "engineeringBottlenecks",
      "contractorCompliance",
      "financeSummary",
      "salesPipeline",
      "contracts",
      "hseHazardsByRisk",
      "recentActivity",
    ],
    quickActions: [],
  },
  PROJECT_MANAGER: {
    focus: "Project execution across the work you run.",
    kpis: ["myProjectCount", "openTaskCount", "overdueTaskCount", "projectsAtRisk"],
    widgets: [
      "attention",
      "announcements",
      "favorites",
      "recentWork",
      "upcomingMeetings",
      "myMeetingActions",
      "myTimesheet",
      "siteToday",
      "upcomingMilestones",
      "engineeringBottlenecks",
      "contractorCompliance",
      "myProjects",
      "openTasks",
      "upcomingDeadlines",
      "projectBudgets",
      "pendingApprovals",
      "purchaseRequests",
      "recentDocuments",
      "recentActivity",
    ],
    quickActions: ["newProject", "newTask", "newPurchaseRequest", "uploadDocument"],
  },
  ARCHITECT: {
    focus: "Design work on the projects you are assigned to.",
    kpis: ["myProjectCount", "openTaskCount", "overdueTaskCount", "documentCount"],
    widgets: [
      "attention",
      "announcements",
      "favorites",
      "recentWork",
      "upcomingMeetings",
      "myMeetingActions",
      "myTimesheet",
      "siteToday",
      "upcomingMilestones",
      "reviewsAwaitingMe",
      "rfisAssignedToMe",
      "myProjects",
      "openTasks",
      "upcomingDeadlines",
      "recentDocuments",
      "recentActivity",
    ],
    quickActions: ["newTask", "uploadDocument"],
  },
  ARCHITECTURE_MANAGER: {
    focus: "Design across every project, and the units waiting to be published.",
    kpis: ["myProjectCount", "openTaskCount", "overdueTaskCount", "documentCount"],
    widgets: [
      "attention",
      "announcements",
      "favorites",
      "recentWork",
      "upcomingMeetings",
      "myMeetingActions",
      "myTimesheet",
      "pendingApprovals",
      "upcomingMilestones",
      "reviewsAwaitingMe",
      "rfisAssignedToMe",
      "myProjects",
      "openTasks",
      "upcomingDeadlines",
      "recentDocuments",
      "recentActivity",
    ],
    quickActions: ["newTask", "uploadDocument"],
  },
  ENGINEER: {
    focus: "Technical delivery on your assigned projects.",
    kpis: ["myProjectCount", "openTaskCount", "openQualityCount", "openIncidentCount"],
    widgets: [
      "attention",
      "announcements",
      "favorites",
      "recentWork",
      "upcomingMeetings",
      "myMeetingActions",
      "myTimesheet",
      "siteToday",
      "upcomingMilestones",
      "rfisAssignedToMe",
      "reviewsAwaitingMe",
      "myProjects",
      "openTasks",
      "qualityRecords",
      "hseHazardsByRisk",
      "recentDocuments",
      "recentActivity",
    ],
    quickActions: ["newTask", "newQualityRecord", "uploadDocument"],
  },
  FINANCE: {
    focus: "Financial operations: invoicing, receivables and budgets.",
    kpis: ["receivables", "overdueValue", "invoicedValue", "openTaskCount"],
    widgets: [
      "attention",
      "announcements",
      "favorites",
      "recentWork",
      "upcomingMeetings",
      "pendingApprovals",
      "overdueInvoices",
      "financeSummary",
      "projectBudgets",
      "openTasks",
      "recentActivity",
    ],
    quickActions: ["newInvoice", "uploadDocument"],
  },
  LEGAL: {
    focus: "Contracts, approvals and legal obligations.",
    kpis: ["activeContracts", "expiringContractCount", "openTaskCount", "clientCount"],
    widgets: [
      "attention",
      "announcements",
      "favorites",
      "recentWork",
      "upcomingMeetings",
      "pendingApprovals",
      "expiringContracts",
      "contractorCompliance",
      "contracts",
      "openTasks",
      "recentActivity",
    ],
    quickActions: ["newContract", "uploadDocument"],
  },
  SALES: {
    focus: "Commercial pipeline and client growth.",
    kpis: ["pipelineValue", "openOpportunityCount", "clientCount", "openTaskCount"],
    widgets: [
      "attention",
      "announcements",
      "favorites",
      "recentWork",
      "upcomingMeetings",
      "pendingApprovals",
      "salesPipeline",
      "openOpportunities",
      "openTasks",
      "recentActivity",
    ],
    quickActions: ["newLead", "newOpportunity", "newClient"],
  },
  SALES_MANAGER: {
    focus: "The sales team's pipeline, and the proposals waiting for your decision.",
    kpis: ["pipelineValue", "openOpportunityCount", "clientCount", "openTaskCount"],
    widgets: [
      "attention",
      "announcements",
      "favorites",
      "recentWork",
      "upcomingMeetings",
      "pendingApprovals",
      "salesPipeline",
      "openOpportunities",
      "openTasks",
      "recentActivity",
    ],
    quickActions: ["newLead", "newOpportunity", "newClient"],
  },
  PROCUREMENT: {
    focus: "Purchasing workflow from request to delivery.",
    kpis: ["openRequests", "openOrders", "lowStockCount", "openTaskCount"],
    widgets: [
      "attention",
      "announcements",
      "favorites",
      "recentWork",
      "upcomingMeetings",
      "pendingApprovals",
      "purchaseRequests",
      "purchaseOrders",
      "lowStock",
      "recentActivity",
    ],
    quickActions: ["newPurchaseRequest", "uploadDocument"],
  },
  INVENTORY: {
    focus: "Material control: stock, movements and replenishment.",
    kpis: ["stockValue", "lowStockCount", "openRequests", "openTaskCount"],
    widgets: [
      "attention",
      "announcements",
      "favorites",
      "recentWork",
      "lowStock",
      "recentMovements",
      "purchaseRequests",
      "recentActivity",
    ],
    quickActions: ["newMovement", "uploadDocument"],
  },
  QAQC: {
    focus: "Quality control across inspections and non-conformances.",
    kpis: ["openQualityCount", "openNcrCount", "openTaskCount", "myProjectCount"],
    widgets: [
      "attention",
      "announcements",
      "favorites",
      "recentWork",
      "upcomingMeetings",
      "pendingApprovals",
      "reviewsAwaitingMe",
      "openNcrs",
      "qualityRecords",
      "openTasks",
      "recentDocuments",
      "recentActivity",
    ],
    quickActions: ["newQualityRecord", "newTask", "uploadDocument"],
  },
  HSE: {
    focus: "Safety performance, incidents and permits.",
    kpis: ["openIncidentCount", "openPermitCount", "openTaskCount", "myProjectCount"],
    widgets: [
      "attention",
      "announcements",
      "favorites",
      "recentWork",
      "upcomingMeetings",
      "pendingApprovals",
      "reviewsAwaitingMe",
      "openIncidents",
      "hseHazardsByRisk",
      "openTasks",
      "recentDocuments",
      "recentActivity",
    ],
    quickActions: ["reportIncident", "newTask", "uploadDocument"],
  },
  VIEWER: {
    focus: "A read-only view of the work you have been given access to.",
    kpis: ["myProjectCount", "openTaskCount", "documentCount", "clientCount"],
    widgets: ["announcements", "favorites", "recentWork", "myProjects", "openTasks", "recentDocuments", "recentActivity"],
    quickActions: [],
  },
};

export function dashboardForRole(role: RoleKey): DashboardConfig {
  return dashboards[role] ?? dashboards.VIEWER;
}
