/**
 * The widget registry (PRD #4 §18, §59).
 *
 * A widget is declared once, with the permission that gates it and the scope it
 * reads under. Widgets are never hardcoded inside a role page — there is no
 * per-role dashboard file anywhere in the codebase (PRD #4 §4, §18).
 *
 * Edge-safe: declaration only, no data access.
 */
import type { ModuleKey } from "./modules";
import type { Permission } from "./permissions";

/** Widget footprints on the dashboard grid (PRD #4 §60). */
export const WIDGET_SIZES = ["SMALL", "MEDIUM", "LARGE", "FULL"] as const;
export type WidgetSize = (typeof WIDGET_SIZES)[number];

/**
 * How a widget presents its data. Each kind has one renderer, so a new widget
 * is a configuration entry rather than a new component (PRD #4 §17).
 */
export type WidgetKind =
  | "list"
  | "breakdown"
  | "alerts"
  | "approvals"
  | "activity"
  | "progress";

export type WidgetDefinition = {
  key: string;
  module: ModuleKey;
  /** Absent from the dashboard entirely when the user lacks this (PRD #4 §19). */
  permission: Permission;
  title: string;
  description?: string;
  kind: WidgetKind;
  size: WidgetSize;
  /** Lower sorts first: critical attention before performance (PRD #4 §62). */
  priority: number;
  /** Where the widget's "view all" leads (PRD #4 §21). */
  href?: string;
  emptyMessage: string;
};

export const widgets: Record<string, WidgetDefinition> = {
  myProjects: {
    key: "myProjects",
    module: "projects",
    permission: "project.view",
    title: "My Projects",
    description: "Projects you manage or are assigned to.",
    kind: "list",
    size: "LARGE",
    priority: 2,
    href: "/projects/my-projects",
    emptyMessage: "Projects assigned to you will appear here.",
  },
  activeProjects: {
    key: "activeProjects",
    module: "projects",
    permission: "project.view",
    title: "Project Status",
    description: "Where the portfolio stands today.",
    kind: "breakdown",
    size: "MEDIUM",
    priority: 3,
    href: "/projects/all",
    emptyMessage: "No projects are visible to you yet.",
  },
  upcomingDeadlines: {
    key: "upcomingDeadlines",
    module: "projects",
    permission: "project.view",
    title: "Upcoming Deadlines",
    description: "Projects finishing soonest.",
    kind: "list",
    size: "MEDIUM",
    priority: 4,
    href: "/projects/all?sort=end-asc",
    emptyMessage: "No project end dates are coming up.",
  },
  upcomingMeetings: {
    key: "upcomingMeetings",
    module: "meetings",
    permission: "meeting.view",
    title: "Upcoming Meetings",
    description: "Your next meetings, today first.",
    kind: "list",
    size: "MEDIUM",
    priority: 3,
    href: "/meetings/mine",
    emptyMessage: "No meetings on your calendar.",
  },
  myMeetingActions: {
    key: "myMeetingActions",
    module: "meetings",
    permission: "meeting.view",
    title: "My Meeting Actions",
    description: "Open actions assigned to you in meetings.",
    kind: "list",
    size: "MEDIUM",
    priority: 4,
    href: "/meetings/actions",
    emptyMessage: "No open actions from meetings.",
  },
  myTimesheet: {
    key: "myTimesheet",
    module: "timesheets",
    permission: "timesheet.submit_own",
    title: "My Timesheet",
    description: "This week's logged time, and the weeks before it.",
    kind: "list",
    size: "MEDIUM",
    priority: 4,
    href: "/timesheets",
    emptyMessage: "No time logged yet.",
  },
  siteToday: {
    key: "siteToday",
    module: "dailyLogs",
    permission: "daily_log.view",
    title: "Site Today",
    description: "The latest daily log on each active project.",
    kind: "list",
    size: "MEDIUM",
    priority: 3,
    href: "/daily-logs",
    emptyMessage: "No active projects to log.",
  },
  announcements: {
    key: "announcements",
    module: "announcements",
    permission: "announcement.view",
    title: "Announcements",
    description: "Critical and pinned notices first, then what you have not read.",
    kind: "list",
    size: "MEDIUM",
    priority: 1,
    href: "/announcements",
    emptyMessage: "No current announcements.",
  },
  rfisAssignedToMe: {
    key: "rfisAssignedToMe",
    module: "engineering",
    permission: "rfi.respond",
    title: "RFIs Assigned to Me",
    description: "Requests for information waiting for your answer, soonest due first.",
    kind: "list",
    size: "MEDIUM",
    priority: 2,
    href: "/engineering/rfis?assignee=me",
    emptyMessage: "No RFI is waiting for your answer.",
  },
  reviewsAwaitingMe: {
    key: "reviewsAwaitingMe",
    module: "engineering",
    permission: "submittal.review",
    title: "Reviews Awaiting Me",
    description: "Submittals and drawings assigned to you for review.",
    kind: "list",
    size: "MEDIUM",
    priority: 2,
    href: "/engineering",
    emptyMessage: "Nothing is waiting for your review.",
  },
  engineeringBottlenecks: {
    key: "engineeringBottlenecks",
    module: "engineering",
    permission: "rfi.view",
    title: "Engineering Bottlenecks",
    description: "RFIs answered late and submittal reviews past their date, across your projects.",
    kind: "list",
    size: "MEDIUM",
    priority: 3,
    href: "/engineering/reports",
    emptyMessage: "No RFI or review is running late.",
  },
  contractorCompliance: {
    key: "contractorCompliance",
    module: "contractors",
    permission: "contractor_compliance.view",
    title: "Contractor Compliance",
    description: "Insurance, licences and guarantees expiring, expired or missing.",
    kind: "list",
    size: "MEDIUM",
    priority: 2,
    href: "/contractors/compliance?alerts=1",
    emptyMessage: "Every contractor's compliance is in date.",
  },
  favorites: {
    key: "favorites",
    module: "dashboard",
    permission: "dashboard.view",
    title: "Favorites",
    description: "The records you starred.",
    kind: "list",
    size: "MEDIUM",
    priority: 2,
    href: "/favorites",
    emptyMessage: "Star a project, task or document to keep it here.",
  },
  recentWork: {
    key: "recentWork",
    module: "dashboard",
    permission: "dashboard.view",
    title: "Recent Work",
    description: "Records you opened lately.",
    kind: "list",
    size: "MEDIUM",
    priority: 2,
    href: "/favorites?tab=recent",
    emptyMessage: "Records you open will appear here.",
  },
  upcomingMilestones: {
    key: "upcomingMilestones",
    module: "projects",
    permission: "project_planning.view",
    title: "Upcoming Milestones",
    description: "Key dates on your projects: delayed first, then the next thirty days.",
    kind: "list",
    size: "MEDIUM",
    priority: 3,
    href: "/projects/milestones",
    emptyMessage: "No milestones due in the next thirty days.",
  },
  criticalMilestones: {
    key: "criticalMilestones",
    module: "projects",
    permission: "project_planning.view",
    title: "Critical Milestones",
    description: "Critical milestones across projects that are delayed, at risk or blocked.",
    kind: "list",
    size: "MEDIUM",
    priority: 2,
    href: "/projects/milestones?critical=1",
    emptyMessage: "No critical milestone is delayed, at risk or blocked.",
  },
  openTasks: {
    key: "openTasks",
    module: "tasks",
    permission: "task.view",
    title: "Open Tasks",
    description: "Work waiting on you.",
    kind: "list",
    size: "LARGE",
    priority: 2,
    href: "/tasks",
    emptyMessage: "You have no open tasks.",
  },
  taskBreakdown: {
    key: "taskBreakdown",
    module: "tasks",
    permission: "task.view",
    title: "Workload",
    description: "Your tasks by state.",
    kind: "breakdown",
    size: "MEDIUM",
    priority: 4,
    href: "/tasks/all",
    emptyMessage: "No tasks are visible to you.",
  },
  attention: {
    key: "attention",
    module: "dashboard",
    permission: "dashboard.view",
    title: "Needs Attention",
    description: "The things that will cost you if they wait.",
    kind: "alerts",
    size: "FULL",
    priority: 0,
    emptyMessage: "Nothing needs your attention right now.",
  },
  /** The top of the Approvals Center's "Waiting for me", most urgent first (PRD #41 §97). */
  pendingApprovals: {
    key: "pendingApprovals",
    module: "approvals",
    permission: "approvals.view",
    title: "Pending Approvals",
    description: "Waiting on your decision.",
    kind: "approvals",
    size: "MEDIUM",
    priority: 1,
    href: "/approvals",
    emptyMessage: "You have nothing to approve.",
  },
  /** Where decisions are piling up, by source, within what this reader may see (PRD #41 §98). */
  approvalBottlenecks: {
    key: "approvalBottlenecks",
    module: "approvals",
    permission: "approvals.history.view",
    title: "Approval Bottlenecks",
    description: "Pending decisions by source, and how long the oldest has waited.",
    kind: "breakdown",
    size: "MEDIUM",
    priority: 4,
    href: "/approvals?tab=history&status=PENDING&sort=oldest",
    emptyMessage: "Nothing is waiting for a decision.",
  },
  recentActivity: {
    key: "recentActivity",
    module: "dashboard",
    permission: "dashboard.view",
    title: "Recent Activity",
    description: "What has changed across your work.",
    kind: "activity",
    size: "MEDIUM",
    priority: 8,
    emptyMessage: "No recent activity.",
  },
  financeSummary: {
    key: "financeSummary",
    module: "finance",
    permission: "finance.invoice.view",
    title: "Invoices",
    description: "Invoice position by status.",
    kind: "breakdown",
    size: "MEDIUM",
    priority: 3,
    href: "/finance/invoices",
    emptyMessage: "No invoices are visible to you.",
  },
  overdueInvoices: {
    key: "overdueInvoices",
    module: "finance",
    permission: "finance.invoice.view",
    title: "Overdue Invoices",
    description: "Past their due date and unpaid.",
    kind: "list",
    size: "MEDIUM",
    priority: 1,
    href: "/finance/invoices?status=OVERDUE",
    emptyMessage: "Nothing is overdue.",
  },
  projectBudgets: {
    key: "projectBudgets",
    module: "finance",
    permission: "finance.project_budget.view",
    title: "Project Financials",
    description: "Invoiced value on your projects.",
    kind: "list",
    size: "MEDIUM",
    priority: 4,
    href: "/finance/project-budgets",
    emptyMessage: "No project financial data is available to you.",
  },
  leaveRequests: {
    key: "leaveRequests",
    module: "hr",
    permission: "hr.leave.view",
    title: "Leave Requests",
    description: "Requests and their state.",
    kind: "list",
    size: "MEDIUM",
    priority: 3,
    href: "/hr/leave",
    emptyMessage: "No leave requests.",
  },
  workforce: {
    key: "workforce",
    module: "hr",
    permission: "hr.employee.view",
    title: "Workforce",
    description: "Company members by department.",
    kind: "breakdown",
    size: "MEDIUM",
    priority: 5,
    href: "/team/departments",
    emptyMessage: "No employee records are visible to you.",
  },
  salesPipeline: {
    key: "salesPipeline",
    module: "sales",
    permission: "sales.opportunity.view",
    title: "Pipeline",
    description: "Opportunity value by stage.",
    kind: "breakdown",
    size: "MEDIUM",
    priority: 3,
    href: "/sales/pipeline",
    emptyMessage: "No opportunities are visible to you.",
  },
  openOpportunities: {
    key: "openOpportunities",
    module: "sales",
    permission: "sales.opportunity.view",
    title: "Open Opportunities",
    description: "Deals still in play.",
    kind: "list",
    size: "MEDIUM",
    priority: 4,
    href: "/sales/opportunities",
    emptyMessage: "No open opportunities.",
  },
  contracts: {
    key: "contracts",
    module: "contracts",
    permission: "legal.contract.view",
    title: "Contracts",
    description: "Contract position by status.",
    kind: "breakdown",
    size: "MEDIUM",
    priority: 3,
    href: "/contracts/contracts",
    emptyMessage: "No contracts are visible to you.",
  },
  expiringContracts: {
    key: "expiringContracts",
    module: "contracts",
    permission: "legal.contract.view",
    title: "Expiring Contracts",
    description: "Ending within 60 days.",
    kind: "list",
    size: "MEDIUM",
    priority: 1,
    href: "/contracts/contracts?status=EXPIRING",
    emptyMessage: "No contracts are expiring soon.",
  },
  purchaseRequests: {
    key: "purchaseRequests",
    module: "procurement",
    permission: "procurement.request.view",
    title: "Purchase Requests",
    description: "Requests by status.",
    kind: "breakdown",
    size: "MEDIUM",
    priority: 3,
    href: "/procurement/requests",
    emptyMessage: "No purchase requests are visible to you.",
  },
  purchaseOrders: {
    key: "purchaseOrders",
    module: "procurement",
    permission: "procurement.order.view",
    title: "Purchase Orders",
    description: "Latest orders raised.",
    kind: "list",
    size: "MEDIUM",
    priority: 4,
    href: "/procurement/orders",
    emptyMessage: "No purchase orders yet.",
  },
  lowStock: {
    key: "lowStock",
    module: "inventory",
    permission: "inventory.item.view",
    title: "Low Stock",
    description: "At or below reorder level.",
    kind: "list",
    size: "MEDIUM",
    priority: 1,
    href: "/inventory/low-stock",
    emptyMessage: "Every item is above its reorder level.",
  },
  recentMovements: {
    key: "recentMovements",
    module: "inventory",
    permission: "inventory.movement.view",
    title: "Recent Movements",
    description: "Stock in, out and adjusted.",
    kind: "list",
    size: "MEDIUM",
    priority: 5,
    href: "/inventory/movements",
    emptyMessage: "No stock movements recorded.",
  },
  qualityRecords: {
    key: "qualityRecords",
    module: "qaqc",
    permission: "qaqc.inspection.view",
    title: "Quality Records",
    description: "Inspections, defects, NCRs and corrective actions.",
    kind: "breakdown",
    size: "MEDIUM",
    priority: 3,
    href: "/qaqc/inspections",
    emptyMessage: "No quality records are visible to you.",
  },
  openNcrs: {
    key: "openNcrs",
    module: "qaqc",
    permission: "qaqc.ncr.view",
    title: "Open NCRs",
    description: "Non-conformances still to close.",
    kind: "list",
    size: "MEDIUM",
    priority: 1,
    href: "/qaqc/ncrs",
    emptyMessage: "No open non-conformances.",
  },
  hseHazardsByRisk: {
    key: "hseHazardsByRisk",
    module: "hse",
    permission: "hse.hazard.view",
    title: "Hazards by risk",
    description: "Open hazards, ranked by the risk they carry.",
    kind: "breakdown",
    size: "MEDIUM",
    priority: 3,
    href: "/hse/hazards",
    emptyMessage: "No open hazards are visible to you.",
  },
  openIncidents: {
    key: "openIncidents",
    module: "hse",
    permission: "hse.incident.view",
    title: "Open Incidents",
    description: "Safety incidents still open.",
    kind: "list",
    size: "MEDIUM",
    priority: 1,
    href: "/hse/incidents",
    emptyMessage: "No open incidents.",
  },
  teamDirectory: {
    key: "teamDirectory",
    module: "team",
    permission: "team.view",
    title: "Team",
    description: "People you work with.",
    kind: "list",
    size: "MEDIUM",
    priority: 6,
    href: "/team",
    emptyMessage: "No team members are visible to you.",
  },
  companyModules: {
    key: "companyModules",
    module: "company",
    permission: "company.view",
    title: "Enabled Modules",
    description: "What is switched on for this company.",
    kind: "breakdown",
    size: "MEDIUM",
    priority: 6,
    href: "/company/modules",
    emptyMessage: "No modules are enabled.",
  },
  recentDocuments: {
    key: "recentDocuments",
    module: "documents",
    permission: "document.view",
    title: "Recent Documents",
    description: "Recently added to your work.",
    kind: "list",
    size: "MEDIUM",
    priority: 6,
    href: "/documents/recent",
    emptyMessage: "No documents yet.",
  },
  supportRequests: {
    key: "supportRequests",
    module: "support",
    permission: "support.request.view",
    title: "Support Requests",
    description: "Open items with the platform team.",
    kind: "list",
    size: "MEDIUM",
    priority: 5,
    href: "/support/requests",
    emptyMessage: "No support requests.",
  },
  userDirectory: {
    key: "userDirectory",
    module: "team",
    permission: "team.manage",
    title: "Users & Roles",
    description: "Who holds which role.",
    kind: "breakdown",
    size: "MEDIUM",
    priority: 4,
    href: "/team",
    emptyMessage: "No users to show.",
  },
};

export const widgetList: WidgetDefinition[] = Object.values(widgets);
