import { Badge } from "@/components/ui/badge";
import { PageHeader } from "@/components/ui/page-header";
import { Table, TableBody, TableCell, TableHead, TableHeaderCell, TableRow } from "@/components/ui/table";
import { requirePlatformContext } from "@/lib/context/platform-context";
import { platformSecurity } from "@/lib/modules/platform/platform-control.query";
import { getTranslations } from "@/lib/i18n/server";
import { enumLabel } from "@/lib/i18n/modules/adminAccess/enum-label";
import { formatDate } from "@/lib/utils/format";
export async function generateMetadata() { const t = await getTranslations("adminAccess"); return { title: t("audit.failedLogins.metaTitle") }; }
export default async function FailedLoginsPage() { const t = await getTranslations("adminAccess"); const context = await requirePlatformContext(); const { failedLogins } = await platformSecurity(context); return <div className="space-y-5"><PageHeader title={t("audit.failedLogins.title")} description={t("audit.failedLogins.description")} /><section className="nesto-card p-5"><Table stack aria-label={t("audit.failedLogins.tableLabel")}><TableHead><TableRow><TableHeaderCell>{t("audit.failedLogins.cols.event")}</TableHeaderCell><TableHeaderCell>{t("audit.failedLogins.cols.user")}</TableHeaderCell><TableHeaderCell>{t("audit.failedLogins.cols.ip")}</TableHeaderCell><TableHeaderCell>{t("audit.failedLogins.cols.device")}</TableHeaderCell><TableHeaderCell>{t("audit.failedLogins.cols.occurred")}</TableHeaderCell></TableRow></TableHead><TableBody>{failedLogins.map((event) => <TableRow key={event.id}><TableCell><Badge tone="danger">{enumLabel(t, "enums.authEvent", event.type)}</Badge></TableCell><TableCell>{event.user ? `${event.user.firstName} ${event.user.lastName}` : t("audit.failedLogins.unknownAccount")}<p className="font-mono text-micro text-fg-subtle">{event.user?.username ?? "—"}</p></TableCell><TableCell className="font-mono text-meta">{event.ipAddress ?? "—"}</TableCell><TableCell className="max-w-sm truncate">{event.userAgent ?? "—"}</TableCell><TableCell>{formatDate(event.createdAt)}</TableCell></TableRow>)}</TableBody></Table></section></div>; }
