import { getTranslations } from "@/lib/i18n/server";
import { enumLabel } from "@/lib/i18n/modules/adminAccess/enum-label";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { PageHeader } from "@/components/ui/page-header";
import { requirePlatformContext } from "@/lib/context/platform-context";
import { platformHealth } from "@/lib/modules/platform/platform-control.query";
export async function generateMetadata() { const t = await getTranslations("adminPlatform"); return { title: t("system.health.metaTitle") }; }
export default async function HealthPage() { const t = await getTranslations("adminPlatform"); const detail = (text: string) => { const known = enumLabel(t, "enums.healthDetail", text, ""); if (known) return known; const provider = /^(.+) provider reachable$/.exec(text); if (provider) return t("enums.healthPattern.providerReachable", { provider: provider[1] }); const queued = /^(\d+) queued$/.exec(text); if (queued) return t("enums.healthPattern.queued", { count: queued[1] }); const failed = /^(\d+) failed deliveries$/.exec(text); if (failed) return t("enums.healthPattern.failedDeliveries", { count: failed[1] }); return text; }; const context = await requirePlatformContext(); const health = await platformHealth(context); const tone = (state: string) => state === "HEALTHY" ? "success" as const : state === "DOWN" ? "danger" as const : "warning" as const; return <div className="space-y-5"><PageHeader title={t("system.health.title")} description={t("system.health.description")} /><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{health.map((item) => <Card key={item.service} className="p-5"><div className="flex items-center justify-between"><h2 className="text-body font-semibold text-fg">{enumLabel(t, "enums.healthService", item.service)}</h2><Badge tone={tone(item.state)}>{enumLabel(t, "enums.health", item.state)}</Badge></div><p className="mt-4 text-table text-fg-muted">{detail(item.detail)}</p></Card>)}</div></div>; }
