import { Badge } from "@/components/ui/badge";
import { CreatePersonButton, CreateUserButton, EditPersonButton } from "@/components/platform/platform-people-actions";
import { PageHeader } from "@/components/ui/page-header";
import { Table, TableBody, TableCell, TableHead, TableHeaderCell, TableRow } from "@/components/ui/table";
import { requirePlatformContext } from "@/lib/context/platform-context";
import { getTranslations } from "@/lib/i18n/server";
import { enumLabel } from "@/lib/i18n/modules/adminAccess/enum-label";
import { listPlatformPeople } from "@/lib/modules/platform/platform-control.query";
import { listParentGroups } from "@/lib/modules/platform/platform.service";

export async function generateMetadata() { const t = await getTranslations("adminAccess"); return { title: t("users.people.metaTitle") }; }
export default async function PeoplePage() { const t = await getTranslations("adminAccess"); const context = await requirePlatformContext(); const [people, groups] = await Promise.all([listPlatformPeople(context), listParentGroups(context, { includeStandalone: true })]); const groupOptions = groups.filter((group) => group.status !== "ARCHIVED").map((group) => ({ value: group.id, label: group.name })); return <div className="space-y-5"><PageHeader title={t("users.people.title")} description={t("users.people.description")} actions={<CreatePersonButton groups={groupOptions} />} /><section className="nesto-card p-5"><Table stack aria-label={t("users.people.tableLabel")}><TableHead><TableRow><TableHeaderCell>{t("users.people.cols.person")}</TableHeaderCell><TableHeaderCell>{t("users.people.cols.parentGroup")}</TableHeaderCell><TableHeaderCell>{t("users.people.cols.jobTitle")}</TableHeaderCell><TableHeaderCell>{t("users.people.cols.lifecycle")}</TableHeaderCell><TableHeaderCell>{t("users.people.cols.userAccount")}</TableHeaderCell><TableHeaderCell>{t("users.people.cols.memberships")}</TableHeaderCell><TableHeaderCell /></TableRow></TableHead><TableBody>{people.map((person) => <TableRow key={person.id}><TableCell><span className="font-medium text-fg">{person.preferredName || `${person.firstName} ${person.lastName}`}</span><p className="text-meta text-fg-subtle">{person.workEmail ?? person.id}</p></TableCell><TableCell>{person.parentGroup.name}</TableCell><TableCell>{person.jobTitle ?? "—"}</TableCell><TableCell><Badge>{enumLabel(t, "enums.lifecycle", person.lifecycleStatus, person.lifecycleStatus.replaceAll("_", " "))}</Badge></TableCell><TableCell>{person.user ? <><span className="font-mono text-meta">{person.user.username}</span><p><Badge tone={person.user.status === "ACTIVE" ? "success" : "danger"}>{enumLabel(t, "enums.accountStatus", person.user.status)}</Badge></p></> : <CreateUserButton personId={person.id} personName={`${person.firstName} ${person.lastName}`} />}</TableCell><TableCell>{person.user?._count.memberships ?? 0}</TableCell><TableCell><EditPersonButton person={person} /></TableCell></TableRow>)}</TableBody></Table></section></div>; }
