import { Badge } from "@/components/ui/badge";
import { CreatePersonButton, CreateUserButton, EditPersonButton } from "@/components/platform/platform-people-actions";
import { PageHeader } from "@/components/ui/page-header";
import { Table, TableBody, TableCell, TableHead, TableHeaderCell, TableRow } from "@/components/ui/table";
import { requirePlatformContext } from "@/lib/context/platform-context";
import { listPlatformPeople } from "@/lib/modules/platform/platform-control.query";
import { listParentGroups } from "@/lib/modules/platform/platform.service";

export const metadata = { title: "People" };
export default async function PeoplePage() { const context = await requirePlatformContext(); const [people, groups] = await Promise.all([listPlatformPeople(context), listParentGroups(context, { includeStandalone: true })]); const groupOptions = groups.filter((group) => group.status !== "ARCHIVED").map((group) => ({ value: group.id, label: group.name })); return <div className="space-y-5"><PageHeader title="People" description="Canonical work profiles only. Private HR and compensation data are excluded." actions={<CreatePersonButton groups={groupOptions} />} /><section className="nesto-card p-5"><Table stack flush aria-label="People"><TableHead><TableRow><TableHeaderCell>Person</TableHeaderCell><TableHeaderCell>Parent Group</TableHeaderCell><TableHeaderCell>Job Title</TableHeaderCell><TableHeaderCell>Lifecycle</TableHeaderCell><TableHeaderCell>User Account</TableHeaderCell><TableHeaderCell>Memberships</TableHeaderCell><TableHeaderCell /></TableRow></TableHead><TableBody>{people.map((person) => <TableRow key={person.id}><TableCell><span className="font-medium text-fg">{person.preferredName || `${person.firstName} ${person.lastName}`}</span><p className="text-meta text-fg-subtle">{person.workEmail ?? person.id}</p></TableCell><TableCell>{person.parentGroup.name}</TableCell><TableCell>{person.jobTitle ?? "—"}</TableCell><TableCell><Badge>{person.lifecycleStatus.replaceAll("_", " ")}</Badge></TableCell><TableCell>{person.user ? <><span className="font-mono text-meta">{person.user.username}</span><p><Badge tone={person.user.status === "ACTIVE" ? "success" : "danger"}>{person.user.status}</Badge></p></> : <CreateUserButton personId={person.id} personName={`${person.firstName} ${person.lastName}`} />}</TableCell><TableCell>{person.user?._count.memberships ?? 0}</TableCell><TableCell><EditPersonButton person={person} /></TableCell></TableRow>)}</TableBody></Table></section></div>; }
