import { PlatformCommandButton } from "@/components/platform/platform-command";
import { Badge } from "@/components/ui/badge";
import { PageHeader } from "@/components/ui/page-header";
import { Table, TableBody, TableCell, TableHead, TableHeaderCell, TableRow } from "@/components/ui/table";
import { requirePlatformContext } from "@/lib/context/platform-context";
import { listPlatformSessions } from "@/lib/modules/platform/platform-control.query";
import { formatDate } from "@/lib/utils/format";

export const metadata = { title: "Sessions" };
export default async function SessionsPage() { const context = await requirePlatformContext(); const sessions = await listPlatformSessions(context); return <div className="space-y-5"><PageHeader title="Sessions" description="Live server sessions. Revocation deletes the session row and takes effect on the next request." /><section className="nesto-card p-5"><Table flush aria-label="Sessions"><TableHead><TableRow><TableHeaderCell>User</TableHeaderCell><TableHeaderCell>Company</TableHeaderCell><TableHeaderCell>Device</TableHeaderCell><TableHeaderCell>IP</TableHeaderCell><TableHeaderCell>Last Active</TableHeaderCell><TableHeaderCell>Expires</TableHeaderCell><TableHeaderCell>Status</TableHeaderCell><TableHeaderCell /></TableRow></TableHead><TableBody>{sessions.map((session) => <TableRow key={session.id}><TableCell><span className="font-medium text-fg">{session.user.firstName} {session.user.lastName}</span><p className="font-mono text-micro text-fg-subtle">{session.user.username}</p></TableCell><TableCell>{session.company?.name ?? "Platform"}</TableCell><TableCell className="max-w-64 truncate" title={session.userAgent ?? undefined}>{session.userAgent ?? "Unknown"}</TableCell><TableCell className="font-mono text-meta">{session.ipAddress ?? "—"}</TableCell><TableCell>{formatDate(session.updatedAt)}</TableCell><TableCell>{formatDate(session.expiresAt)}</TableCell><TableCell><Badge tone={session.active ? "success" : "danger"}>{session.active ? "ACTIVE" : "EXPIRED"}</Badge></TableCell><TableCell>{session.id === context.sessionId ? <span className="text-meta text-fg-subtle">Current</span> : <PlatformCommandButton label="Revoke" title="Revoke session" action="session.revoke" fixed={{ sessionId: session.id }} reasonOnly destructive variant="danger" success="Session revoked." />}</TableCell></TableRow>)}</TableBody></Table></section></div>; }
