import { SceneConfigurationButton, ThreeDModelUploadButton } from "@/components/platform/three-d-actions";
import { PlatformCommandButton } from "@/components/platform/platform-command";
import { Badge } from "@/components/ui/badge";
import { PageHeader } from "@/components/ui/page-header";
import { requirePlatformContext } from "@/lib/context/platform-context";
import { listPlatformProjects, listThreeDProjects } from "@/lib/modules/platform/platform-control.query";

export const metadata = { title: "3D Platform" };
export default async function ThreeDPage() { const context = await requirePlatformContext(); const [configs, projects] = await Promise.all([listThreeDProjects(context), listPlatformProjects(context)]); const available = projects.filter((project) => !project.threeD && !project.archivedAt); return <div className="space-y-5"><PageHeader title="3D Platform" description="Model administration, scene configuration and publishing. Tenant users receive only the published viewer." actions={available.length ? <PlatformCommandButton label="Provision project" title="Provision 3D project" action="3d.provision" variant="primary" success="3D project provisioned." fields={[{ name: "projectId", label: "Canonical project", type: "select", required: true, options: available.map((project) => ({ value: project.id, label: `${project.company.name} · ${project.code} · ${project.name}` })) }, { name: "reason", label: "Reason", type: "textarea", required: true }]} /> : undefined} />
  <div className="space-y-4">{configs.map((config) => <section key={config.id} className="nesto-card p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-meta font-medium uppercase tracking-wide text-fg-subtle">{config.project.company.parentGroup.name} · {config.project.company.name}</p><h2 className="mt-1 text-card font-semibold text-fg">{config.project.name}</h2><p className="font-mono text-meta text-fg-subtle">{config.project.code}</p></div><Badge tone={config.status === "PUBLISHED" ? "success" : config.status === "ERROR" ? "danger" : "info"}>{config.status}</Badge></div><div className="mt-5 grid gap-5 xl:grid-cols-[1fr_auto]"><div>{config.versions.length ? <div className="divide-y divide-line rounded-lg border border-line">{config.versions.map((version) => <div key={version.id} className="flex flex-wrap items-center justify-between gap-3 px-4 py-3"><span><span className="font-medium text-fg">v{version.version} · {version.name}</span><span className="ml-2 text-meta text-fg-subtle">{version.sourceFileName ?? version.storageKey ?? "registered model"}</span></span><div className="flex items-center gap-2"><Badge tone={version.status === "PUBLISHED" ? "success" : version.status === "FAILED" ? "danger" : "neutral"}>{version.status}</Badge>{["READY", "PUBLISHED", "RETIRED"].includes(version.status) && version.id !== config.publishedVersionId ? <PlatformCommandButton label="Publish" title={`Publish v${version.version}?`} description="This replaces the tenant viewer's published version. The previous version remains available for rollback." action="3d.publish" fixed={{ configurationId: config.id, versionId: version.id }} reasonOnly submitLabel="Publish version" success="3D version published." /> : null}</div></div>)}</div> : <p className="rounded-lg border border-dashed border-line p-5 text-table text-fg-muted">No model versions uploaded.</p>}</div><div className="flex flex-wrap items-start gap-2"><ThreeDModelUploadButton configurationId={config.id} /><SceneConfigurationButton configurationId={config.id} initial={config.sceneConfiguration} /></div></div></section>)}</div></div>; }
