import { z } from "zod";

import { PROJECT_3D_SCHEMA_VERSION, PROJECT_3D_SLOT_ROLES } from "./contracts";

export const project3DSceneNodeSchema = z.object({
  nodeId: z.string().min(1),
  name: z.string(),
  meshIndex: z.number().int().nonnegative().nullable(),
  parentNodeId: z.string().nullable(),
  depth: z.number().int().nonnegative(),
  isMesh: z.boolean(),
  autoClassification: z.enum(["unit_block", "architecture"]),
});
export const project3DUnitBindingSchema = z.object({
  meshName: z.string().min(1),
  unitId: z.string().min(1),
  unitCode: z.string().min(1),
  poiYawDeg: z.number(),
  poiEnabled: z.boolean(),
  poiDistanceOverride: z.number().nullable(),
  poiHeightOverride: z.number().nullable(),
});

export const project3DNodeOverrideSchema = z.object({
  nodeId: z.string().min(1),
  classification: z.enum(["architecture", "landscape", "interaction", "helper"]).optional(),
  materialPreset: z.enum(["concrete", "plaster", "stone", "wood", "aluminium", "steel", "chrome", "ceramic"]).optional(),
  colorHex: z.string().optional(),
  roughness: z.number().optional(),
  metalness: z.number().optional(),
  opacity: z.number().optional(),
  clearcoat: z.number().optional(),
  clearcoatRoughness: z.number().optional(),
  iridescence: z.number().optional(),
  iridescenceIOR: z.number().optional(),
  visible: z.boolean().optional(),
  materialOverrideEnabled: z.boolean().optional(),
  baseTextureEnabled: z.boolean().optional(),
  roughnessMapEnabled: z.boolean().optional(),
  metalnessMapEnabled: z.boolean().optional(),
  normalMapEnabled: z.boolean().optional(),
  normalStrength: z.number().optional(),
  aoMapEnabled: z.boolean().optional(),
  emissiveEnabled: z.boolean().optional(),
  emissiveMapEnabled: z.boolean().optional(),
  emissiveColorHex: z.string().optional(),
  emissiveIntensity: z.number().optional(),
  transmissionEnabled: z.boolean().optional(),
  transmission: z.number().optional(),
  ior: z.number().optional(),
  thickness: z.number().optional(),
  attenuationEnabled: z.boolean().optional(),
  attenuationColorHex: z.string().optional(),
  attenuationDistance: z.number().optional(),
  anisotropy: z.number().optional(),
  anisotropyRotation: z.number().optional(),
  sheen: z.number().optional(),
  sheenColorHex: z.string().optional(),
  sheenRoughness: z.number().optional(),
  dispersion: z.number().optional(),
  textureTransformEnabled: z.boolean().optional(),
  mapScaleX: z.number().optional(),
  mapScaleY: z.number().optional(),
  mapOffsetX: z.number().optional(),
  mapOffsetY: z.number().optional(),
  mapRotation: z.number().optional(),
});

export const project3DModelTransformSchema = z.object({
  scale: z.number().positive(),
  rotationDeg: z.number(),
  altitudeOffset: z.number(),
  positionX: z.number(),
  positionZ: z.number(),
  rotationXDeg: z.number(),
  rotationZDeg: z.number(),
});

export const project3DReleaseManifestSchema = z.object({
  schemaVersion: z.literal(PROJECT_3D_SCHEMA_VERSION),
  projectId: z.string().min(1),
  companyId: z.string().min(1),
  releaseId: z.string().min(1),
  releaseNumber: z.number().int().positive(),
  createdAt: z.string().datetime(),
  experience: z.record(z.string(), z.unknown()),
  models: z.array(z.object({
    slotId: z.string().min(1),
    slotName: z.string().min(1),
    slotRole: z.enum(PROJECT_3D_SLOT_ROLES),
    transformParentSlotId: z.string().min(1).nullable(),
    versionId: z.string().min(1),
    versionNumber: z.number().int().positive(),
    runtimeStorageKey: z.string().min(1),
    runtimeFileName: z.string().min(1),
    runtimeContentType: z.literal("model/gltf-binary"),
    transform: project3DModelTransformSchema,
    visible: z.boolean(),
    castShadow: z.boolean(),
    receiveShadow: z.boolean(),
    selectable: z.boolean(),
    sceneManifest: z.array(project3DSceneNodeSchema),
    nodeOverrides: z.array(project3DNodeOverrideSchema),
    unitBindings: z.array(project3DUnitBindingSchema),
  })).min(1),
});
