import { getTranslations } from "@/lib/i18n/server";
import { enumLabel } from "@/lib/i18n/modules/adminAccess/enum-label";
import { PlatformCommandButton } from "@/components/platform/platform-command";
import { Badge } from "@/components/ui/badge";
import { PageHeader } from "@/components/ui/page-header";
import { Table, TableBody, TableCell, TableHead, TableHeaderCell, TableRow } from "@/components/ui/table";
import { requirePlatformContext } from "@/lib/context/platform-context";
import { platformSupport } from "@/lib/modules/platform/platform-control.query";
import { formatDate } from "@/lib/utils/format";

export async function generateMetadata() { const t = await getTranslations("adminPlatform"); return { title: t("system.support.metaTitle") }; }
export default async function SupportPage() { const t = await getTranslations("adminPlatform"); const context = await requirePlatformContext(); const data = await platformSupport(context); return <div className="space-y-5"><PageHeader title={t("system.support.title")} description={t("system.support.description")} actions={<PlatformCommandButton label={t("system.support.open")} title={t("system.support.openTitle")} description={t("system.support.openDescription")} action="support.create" variant="primary" success={t("system.support.openSuccess")} fields={[{ name: "parentGroupId", label: t("system.support.fields.parentGroup"), type: "select", options: data.groups.map((row) => ({ value: row.id, label: row.name })), emptyLabel: t("system.support.fields.noGroup") }, { name: "companyId", label: t("system.support.fields.company"), type: "select", options: data.companies.map((row) => ({ value: row.id, label: row.name })), emptyLabel: t("system.support.fields.noCompany") }, { name: "projectId", label: t("system.support.fields.project"), type: "select", options: data.projects.map((row) => ({ value: row.id, label: `${row.code} · ${row.name}` })), emptyLabel: t("system.support.fields.noProject") }, { name: "targetUserId", label: t("system.support.fields.user"), type: "select", options: data.users.map((row) => ({ value: row.id, label: `${row.firstName} ${row.lastName} (${row.username})` })), emptyLabel: t("system.support.fields.noUser") }, { name: "durationMinutes", label: t("system.support.fields.duration"), type: "number", required: true }, { name: "reason", label: t("system.support.fields.reason"), type: "textarea", required: true }]} initial={{ durationMinutes: 30 }} />} />
  <nav className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5" aria-label={t("system.support.linksLabel")}>{[{ href: "/admin/users", label: t("system.support.links.users.label"), detail: t("system.support.links.users.detail", { count: data.users.length }) }, { href: "/admin/organizations?type=company", label: t("system.support.links.companies.label"), detail: t("system.support.links.companies.detail", { count: data.companies.length }) }, { href: "/admin/projects", label: t("system.support.links.projects.label"), detail: t("system.support.links.projects.detail", { count: data.projects.length }) }, { href: "/admin/users/inspector", label: t("system.support.links.inspector.label"), detail: t("system.support.links.inspector.detail") }, { href: "/admin/audit", label: t("system.support.links.audit.label"), detail: t("system.support.links.audit.detail") }].map((item) => <Link key={item.href} href={item.href} className="nesto-card p-4 transition hover:border-accent"><span className="font-medium text-fg">{item.label}</span><span className="mt-1 block text-meta text-fg-subtle">{item.detail}</span></Link>)}</nav>
  <section className="nesto-card p-5"><Table stack aria-label={t("system.support.tableLabel")}><TableHead><TableRow><TableHeaderCell>{t("system.support.cols.target")}</TableHeaderCell><TableHeaderCell>{t("system.support.cols.reason")}</TableHeaderCell><TableHeaderCell>{t("system.support.cols.expires")}</TableHeaderCell><TableHeaderCell>{t("system.support.cols.status")}</TableHeaderCell><TableHeaderCell /></TableRow></TableHead><TableBody>{data.sessions.map((session) => <TableRow key={session.id}><TableCell><span className="font-mono text-meta">{session.projectId ?? session.companyId ?? session.parentGroupId ?? session.targetUserId}</span><p className="text-micro text-fg-subtle">{enumLabel(t, "enums.supportTarget", session.projectId ? "Project" : session.companyId ? "Company" : session.parentGroupId ? "Parent Group" : "User")}</p></TableCell><TableCell className="max-w-lg">{session.reason}</TableCell><TableCell>{formatDate(session.expiresAt)}</TableCell><TableCell><Badge tone={session.active ? "warning" : "neutral"}>{enumLabel(t, "enums.supportState", session.active ? "ACTIVE" : session.revokedAt ? "REVOKED" : "EXPIRED")}</Badge></TableCell><TableCell>{session.active ? <PlatformCommandButton label={t("common.revoke")} title={t("system.support.revokeTitle")} action="support.revoke" fixed={{ supportSessionId: session.id }} reasonOnly destructive variant="danger" success={t("system.support.revoked")} /> : null}</TableCell></TableRow>)}</TableBody></Table></section></div>; }
import Link from "@/components/navigation/nav-link";
