import { PlatformCommandButton } from "@/components/platform/platform-command";
import { Badge } from "@/components/ui/badge";
import { PageHeader } from "@/components/ui/page-header";
import { Table, TableBody, TableCell, TableHead, TableHeaderCell, TableRow } from "@/components/ui/table";
import { requirePlatformContext } from "@/lib/context/platform-context";
import { platformSupport } from "@/lib/modules/platform/platform-control.query";
import { formatDate } from "@/lib/utils/format";

export const metadata = { title: "Support" };
export default async function SupportPage() { const context = await requirePlatformContext(); const data = await platformSupport(context); return <div className="space-y-5"><PageHeader title="Support workspace" description="Find structural records and explicitly request short-lived access before opening sensitive tenant data." actions={<PlatformCommandButton label="Open sensitive support access" title="Open sensitive support access" description="The reason and target are audited. Access expires automatically and does not change the tenant user's own permissions." action="support.create" variant="primary" success="Support access opened." fields={[{ name: "parentGroupId", label: "Parent group", type: "select", options: data.groups.map((row) => ({ value: row.id, label: row.name })), emptyLabel: "No group target" }, { name: "companyId", label: "Company", type: "select", options: data.companies.map((row) => ({ value: row.id, label: row.name })), emptyLabel: "No company target" }, { name: "projectId", label: "Project", type: "select", options: data.projects.map((row) => ({ value: row.id, label: `${row.code} · ${row.name}` })), emptyLabel: "No project target" }, { name: "targetUserId", label: "User", type: "select", options: data.users.map((row) => ({ value: row.id, label: `${row.firstName} ${row.lastName} (${row.username})` })), emptyLabel: "No user target" }, { name: "durationMinutes", label: "Duration (minutes)", type: "number", required: true }, { name: "reason", label: "Support reason", type: "textarea", required: true }]} initial={{ durationMinutes: 30 }} />} />
  <nav className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5" aria-label="Support record links">{[{ href: "/admin/users", label: "User accounts", detail: `${data.users.length} users` }, { href: "/admin/organizations?type=company", label: "Companies", detail: `${data.companies.length} companies` }, { href: "/admin/projects", label: "Projects", detail: `${data.projects.length} projects` }, { href: "/admin/users/inspector", label: "Access inspector", detail: "Explain effective access" }, { href: "/admin/audit", label: "Global audit", detail: "Trace sensitive changes" }].map((item) => <Link key={item.href} href={item.href} className="nesto-card p-4 transition hover:border-accent"><span className="font-medium text-fg">{item.label}</span><span className="mt-1 block text-meta text-fg-subtle">{item.detail}</span></Link>)}</nav>
  <section className="nesto-card p-5"><Table stack flush aria-label="Support access"><TableHead><TableRow><TableHeaderCell>Target</TableHeaderCell><TableHeaderCell>Reason</TableHeaderCell><TableHeaderCell>Expires</TableHeaderCell><TableHeaderCell>Status</TableHeaderCell><TableHeaderCell /></TableRow></TableHead><TableBody>{data.sessions.map((session) => <TableRow key={session.id}><TableCell><span className="font-mono text-meta">{session.projectId ?? session.companyId ?? session.parentGroupId ?? session.targetUserId}</span><p className="text-micro text-fg-subtle">{session.projectId ? "Project" : session.companyId ? "Company" : session.parentGroupId ? "Parent Group" : "User"}</p></TableCell><TableCell className="max-w-lg">{session.reason}</TableCell><TableCell>{formatDate(session.expiresAt)}</TableCell><TableCell><Badge tone={session.active ? "warning" : "neutral"}>{session.active ? "ACTIVE" : session.revokedAt ? "REVOKED" : "EXPIRED"}</Badge></TableCell><TableCell>{session.active ? <PlatformCommandButton label="Revoke" title="Revoke support access" action="support.revoke" fixed={{ supportSessionId: session.id }} reasonOnly destructive variant="danger" success="Support access revoked." /> : null}</TableCell></TableRow>)}</TableBody></Table></section></div>; }
import Link from "@/components/navigation/nav-link";
