import { getTranslations } from "@/lib/i18n/server";
import { PlatformCommandButton } from "@/components/platform/platform-command";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { PageHeader } from "@/components/ui/page-header";
import { requirePlatformContext } from "@/lib/context/platform-context";
import { maintenanceState } from "@/lib/modules/platform/platform-control.query";

export async function generateMetadata() { const t = await getTranslations("adminPlatform"); return { title: t("system.maintenance.metaTitle") }; }
const controls = [{ key: "maintenance.enabled", prop: "enabled" }, { key: "maintenance.readOnly", prop: "readOnly" }, { key: "maintenance.disableUploads", prop: "disableUploads" }, { key: "maintenance.disableNewLogins", prop: "disableNewLogins" }, { key: "maintenance.disable3DProcessing", prop: "disable3DProcessing" }] as const;
export default async function MaintenancePage() { const t = await getTranslations("adminPlatform"); await requirePlatformContext(); const state = await maintenanceState(); return <div className="space-y-5"><PageHeader title={t("system.maintenance.title")} description={t("system.maintenance.description")} /><div className="space-y-3">{controls.map((control) => { const active = state[control.prop]; const label = t(`system.maintenance.controls.${control.prop}.label` as never); const description = t(`system.maintenance.controls.${control.prop}.description` as never); return <Card key={control.key} className="flex flex-wrap items-center justify-between gap-5 p-5"><div className="max-w-3xl"><div className="flex items-center gap-2"><h2 className="text-body font-semibold text-fg">{label}</h2><Badge tone={active ? "warning" : "success"}>{active ? t("system.maintenance.on") : t("system.maintenance.off")}</Badge></div><p className="mt-1 text-table text-fg-muted">{description}</p></div><PlatformCommandButton label={active ? t("system.maintenance.turnOff") : t("system.maintenance.enable")} title={active ? t("system.maintenance.turnOffTitle", { label: label.toLowerCase() }) : t("system.maintenance.enableTitle", { label: label.toLowerCase() })} description={t("system.maintenance.dialogDescription")} action="maintenance.save" fixed={{ key: control.key, enabled: !active }} reasonOnly destructive={!active} variant={active ? "secondary" : "danger"} success={active ? t("system.maintenance.disabledSuccess", { label }) : t("system.maintenance.enabledSuccess", { label })} /></Card>; })}</div></div>; }
