import { getTranslations } from "@/lib/i18n/server";
import { Badge } from "@/components/ui/badge";
import { PageHeader } from "@/components/ui/page-header";
import { Table, TableBody, TableCell, TableHead, TableHeaderCell, TableRow } from "@/components/ui/table";
import { requirePlatformContext } from "@/lib/context/platform-context";
import { platformOperations } from "@/lib/modules/platform/platform-control.query";
import { formatDate } from "@/lib/utils/format";
export async function generateMetadata() { const t = await getTranslations("adminPlatform"); return { title: t("system.jobs.metaTitle") }; }
export default async function JobsPage() { const t = await getTranslations("adminPlatform"); const context = await requirePlatformContext(); const data = await platformOperations(context); return <div className="space-y-6"><PageHeader title={t("system.jobs.title")} description={t("system.jobs.description")} /><section className="nesto-card p-5"><h2 className="mb-4 text-card font-semibold">{t("system.jobs.scheduled")}</h2><Table stack aria-label={t("system.jobs.tableLabel")}><TableHead><TableRow><TableHeaderCell>{t("system.jobs.cols.job")}</TableHeaderCell><TableHeaderCell>{t("system.jobs.cols.lastRun")}</TableHeaderCell><TableHeaderCell>{t("system.jobs.cols.lastSuccess")}</TableHeaderCell><TableHeaderCell>{t("system.jobs.cols.processed")}</TableHeaderCell><TableHeaderCell>{t("system.jobs.cols.failures")}</TableHeaderCell><TableHeaderCell>{t("system.jobs.cols.status")}</TableHeaderCell></TableRow></TableHead><TableBody>{data.heartbeats.map((job) => <TableRow key={job.job}><TableCell className="font-mono text-meta">{job.job}</TableCell><TableCell>{job.lastRunAt ? formatDate(job.lastRunAt) : t("common.never")}</TableCell><TableCell>{job.lastSuccessAt ? formatDate(job.lastSuccessAt) : t("common.never")}</TableCell><TableCell>{job.lastProcessed}</TableCell><TableCell>{job.failures}</TableCell><TableCell><Badge tone={job.consecutiveFailures ? "danger" : "success"}>{job.consecutiveFailures ? t("system.jobs.failed") : t("system.jobs.healthy")}</Badge></TableCell></TableRow>)}</TableBody></Table></section><section className="nesto-card p-5"><h2 className="mb-4 text-card font-semibold">{t("system.jobs.recent")}</h2><Table stack aria-label={t("system.jobs.failuresLabel")}><TableHead><TableRow><TableHeaderCell>{t("system.jobs.failureCols.job")}</TableHeaderCell><TableHeaderCell>{t("system.jobs.failureCols.error")}</TableHeaderCell><TableHeaderCell>{t("system.jobs.failureCols.attempt")}</TableHeaderCell><TableHeaderCell>{t("system.jobs.failureCols.failed")}</TableHeaderCell><TableHeaderCell>{t("system.jobs.failureCols.status")}</TableHeaderCell></TableRow></TableHead><TableBody>{data.failures.map((failure) => <TableRow key={failure.id}><TableCell className="font-mono text-meta">{failure.jobKey}</TableCell><TableCell><span className="font-medium text-fg">{failure.errorCode}</span><p className="max-w-xl truncate text-meta text-fg-subtle">{failure.errorMessage}</p></TableCell><TableCell>{failure.attempt}</TableCell><TableCell>{formatDate(failure.failedAt)}</TableCell><TableCell><Badge tone={failure.retriedAt ? "neutral" : failure.retryable ? "warning" : "danger"}>{failure.retriedAt ? t("system.jobs.retried") : failure.retryable ? t("system.jobs.retryable") : t("system.jobs.failed")}</Badge></TableCell></TableRow>)}</TableBody></Table></section></div>; }
