import { PlatformCommandButton } from "@/components/platform/platform-command";
import { Badge } from "@/components/ui/badge";
import { PageHeader } from "@/components/ui/page-header";
import { Table, TableBody, TableCell, TableHead, TableHeaderCell, TableRow } from "@/components/ui/table";
import { MODULE_KEYS, modules } from "@/config/modules";
import { requirePlatformContext } from "@/lib/context/platform-context";
import { listPlatformGrants, listPlatformUsers } from "@/lib/modules/platform/platform-control.query";
import { listParentGroups } from "@/lib/modules/platform/platform.service";
import { formatDate } from "@/lib/utils/format";

export const metadata = { title: "Access Grants" };
export default async function GrantsPage() { const context = await requirePlatformContext(); const [grants, users, groups] = await Promise.all([listPlatformGrants(context), listPlatformUsers(context), listParentGroups(context)]); return <div className="space-y-5"><PageHeader title="Access grants" description="Explicit generic grants. Revoked and expired grants remain as history." actions={<PlatformCommandButton label="Create grant" title="Create access grant" description="The target must belong to the selected parent group. Group and company grants participate in effective module access." action="grant.create" variant="primary" success="Access granted." fields={[{ name: "userId", label: "User", type: "select", required: true, options: users.filter((row) => !row.platformAccess).map((row) => ({ value: row.id, label: `${row.firstName} ${row.lastName} (${row.username})` })) }, { name: "parentGroupId", label: "Parent group", type: "select", required: true, options: groups.map((row) => ({ value: row.id, label: row.name })) }, { name: "moduleKey", label: "Module", type: "select", required: true, options: MODULE_KEYS.map((value) => ({ value, label: modules[value].label })) }, { name: "scopeType", label: "Scope", type: "select", required: true, options: ["GROUP", "COMPANY", "PROJECT"].map((value) => ({ value, label: value })) }, { name: "scopeId", label: "Scope record ID", type: "text", required: true, hint: "Use the selected group's ID for a group grant." }, { name: "accessLevel", label: "Access level", type: "select", required: true, options: ["VIEW", "CONTRIBUTE", "APPROVE", "MANAGE"].map((value) => ({ value, label: value })) }, { name: "expiresAt", label: "Expires", type: "date" }, { name: "reason", label: "Reason", type: "textarea", required: true }]} />} />
  <section className="nesto-card p-5"><Table flush aria-label="Access grants"><TableHead><TableRow><TableHeaderCell>Holder</TableHeaderCell><TableHeaderCell>Group</TableHeaderCell><TableHeaderCell>Module</TableHeaderCell><TableHeaderCell>Scope</TableHeaderCell><TableHeaderCell>Level</TableHeaderCell><TableHeaderCell>Expires</TableHeaderCell><TableHeaderCell>Status</TableHeaderCell><TableHeaderCell /></TableRow></TableHead><TableBody>{grants.map((grant) => { const live = !grant.revokedAt && (!grant.expiresAt || new Date(grant.expiresAt) > new Date()); return <TableRow key={grant.id}><TableCell><span className="font-medium text-fg">{grant.user.firstName} {grant.user.lastName}</span><p className="font-mono text-micro text-fg-subtle">{grant.user.username}</p></TableCell><TableCell>{grant.parentGroup.name}</TableCell><TableCell>{grant.functionKey ?? "—"}</TableCell><TableCell>{grant.scopeType}<p className="font-mono text-micro text-fg-subtle">{grant.scopeId}</p></TableCell><TableCell>{grant.accessLevel}</TableCell><TableCell>{grant.expiresAt ? formatDate(grant.expiresAt) : "No expiry"}</TableCell><TableCell><Badge tone={live ? "success" : "danger"}>{grant.revokedAt ? "REVOKED" : live ? "LIVE" : "EXPIRED"}</Badge></TableCell><TableCell>{live ? <PlatformCommandButton label="Revoke" title="Revoke access grant" action="grant.revoke" fixed={{ grantId: grant.id }} reasonOnly destructive variant="danger" success="Grant revoked." /> : null}</TableCell></TableRow>; })}</TableBody></Table></section></div>; }
